(()=>{
'use strict';
const C=window.VillsporCore;
const $=id=>document.getElementById(id);
const canvas=$('game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const TILE=32,WORLD={w:60,h:28};
const SAVE_KEY='villspor-save-v1',BEST_KEY='villspor-best-v1';
const runtimeConfig={playerSpeed:142,encounterChance:.1,encounterMin:130,encounterRange:100,roamerEnabled:true,fallbackEncounters:0,debugActive:false};
const encounters={forest:['gnistrev','mosemurr','bekkskvett','kongleklo','fjordfnugg'],cave:['kullvinge','gnistrev','bekkskvett'],fjord:['lynglo','ravnbluss','stormhjort','fjordfnugg']};
const ROAMER_ZONES={
 forest:{ids:encounters.forest,max:3,spots:[[20.5,6.5],[25.5,8.5],[21.5,19.5]]},
 cave:{ids:encounters.cave,max:2,spots:[[31.5,11.5],[39.5,18.5]]},
 fjord:{ids:encounters.fjord,max:3,spots:[[45.5,8.5],[53.5,12.5],[55.5,10.5]]}
};
const CAMP_FRIEND_SLOTS=[[3.5,13.5],[5.5,22.5],[12.5,22.5],[2.5,22.5]];
const CAMP_LINES={gnistrev:'Gnistrev tegner varme sirkler i gresset.',mosemurr:'Mosemurr har funnet den mykeste plassen ved campingen.',bekkskvett:'Bekkskvett lytter etter bølgene nedenfor bobilen.',kongleklo:'Kongleklo sorterer blanke småstein i en sirkel.',fjordfnugg:'Fjordfnugg løfter vingene mot vinden fra fjorden.',kullvinge:'Kullvinge tegner et lite sotmerke uten å skremme noen.',lynglo:'Lynglo gjemmer små blomster rundt treningsringen.',ravnbluss:'Ravnbluss holder vakt fra taket på verkstedet.',stormhjort:'Stormhjort lytter til fjorden vest for bobilen.',flammefyrsten:'Flammefyrsten folder vingene sammen. Hele leiren kjennes tryggere.'};
const MATERIALS={wood:{name:'Furuved',icon:'🪵'},crystal:{name:'Glødestein',icon:'💎'},herb:{name:'Villurt',icon:'🌿'}};
const BASE_DEFS={
 workshop:{name:'Roglassverksted',icon:'🧿',x:1,y:12,type:'ILD',effect:'Kortere sporsans-cooldown og sterkere Roglass',costs:[{wood:1,crystal:1},{wood:2,crystal:2},{wood:3,crystal:4}]},
 training:{name:'Treningsring',icon:'⚔️',x:9,y:11,type:'VEKST',effect:'Gir den bemannede reservevennen XP etter seier',costs:[{wood:1,herb:1},{wood:3,herb:2},{wood:5,crystal:2,herb:2}]},
 garden:{name:'Bærhage',icon:'🫐',x:12,y:17,type:'VANN',effect:'Dyrker villbær gjennom ekspedisjonsseire',costs:[{wood:1,herb:1},{wood:2,herb:3},{wood:3,crystal:1,herb:5}]}
};
const RESOURCE_NODES=[
 {id:'wood-a',kind:'wood',x:16,y:18,amount:3},{id:'wood-b',kind:'wood',x:17,y:5,amount:3},{id:'wood-c',kind:'wood',x:27,y:17,amount:3},
 {id:'crystal-a',kind:'crystal',x:31,y:20,amount:3},{id:'crystal-b',kind:'crystal',x:35,y:7,amount:3},{id:'crystal-c',kind:'crystal',x:37,y:20,amount:3},
 {id:'herb-a',kind:'herb',x:10,y:23,amount:3},{id:'herb-b',kind:'herb',x:27,y:22,amount:3},{id:'herb-c',kind:'herb',x:44,y:19,amount:3}
];
const TRAINERS=[
 {id:'runa',name:'Stisøker Runa',x:46*TILE,y:15*TILE,icon:'🧣',color:'#8d5d8f',enemy:'lynglo',level:4,reward:{wood:2,herb:2}},
 {id:'aksel',name:'Fjordlos Aksel',x:51*TILE,y:12*TILE,icon:'⛵',color:'#486f91',enemy:'ravnbluss',level:5,reward:{crystal:2,herb:1}},
 {id:'inga',name:'Fjordvokter Inga',x:57*TILE,y:14*TILE,icon:'⚓',color:'#3f7180',enemy:'stormhjort',level:6,reward:{wood:3,crystal:3,herb:3},guardian:true}
];
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');
let reducedMotion=motionQuery.matches;
const updateMotionPreference=e=>{reducedMotion=e.matches;};
if(motionQuery.addEventListener)motionQuery.addEventListener('change',updateMotionPreference);else motionQuery.addListener?.(updateMotionPreference);
const keys=new Set();
let raf=0,last=0,toastTimer=0,audioCtx=null,lastPanelUpdate=0,uiMode='';

const fresh=()=>({
 mode:'title',started:false,paused:false,player:{x:6*TILE,y:14*TILE,dir:'down',speed:142},trail:[],ninni:{x:5.5*TILE,y:14.5*TILE},camera:{x:0,y:0},
 team:[],reserve:[],seen:[],caught:[],quest:0,bossDefeated:false,endingType:null,dialogs:{tora:false,loke:false,siv:false,fjordGate:false},sideQuests:{loke:'available',siv:'available'},nightTrail:{stage:0,completed:false,rewarded:false},secrets:[],trial:{completed:false,active:false,wins:0,runs:0,bestBerries:null,berriesUsed:0},relics:[],inventory:{berries:2,wood:0,crystal:0,herb:0},
 base:{buildings:{workshop:0,training:0,garden:0},assignments:{workshop:null,training:null,garden:null},gardenCharge:0},gathered:[],trainers:{runa:0,aksel:0,inga:0,fjordMark:false},
 roamers:[],roamerSpawnAt:{forest:0,cave:0,fjord:0},scent:{activeUntil:0,cooldownUntil:0,target:null},particles:createAmbience(),
 moved:0,encounterCooldown:150,startTime:0,elapsed:0,best:Number(localStorage.getItem(BEST_KEY)||0),battle:null,message:'',sound:true,lastSave:0
});
let game=fresh(),campFriendCache=[];
const creatureArt={};for(const id of Object.keys(C.CREATURES)){const img=new Image();img.decoding='async';img.src=`assets/creatures/${id}.svg`;creatureArt[id]=img;}
let panelSignature='',bestiarySignature='';

const NPCS=[
 {id:'tora',name:'Bestemor Tora',x:7*TILE,y:11*TILE,icon:'👵',color:'#a45248'},
 {id:'loke',name:'Loke',x:12*TILE,y:18*TILE,icon:'🧒',color:'#4c78a8'},
 {id:'siv',name:'Skogvokter Siv',x:23*TILE,y:9*TILE,icon:'🧭',color:'#5f8152'}
];
const PROPS=[
 {kind:'tent',x:3,y:6},{kind:'tent',x:10,y:7},{kind:'camper',x:4,y:19},{kind:'fire',x:9,y:18},
 {kind:'sign',x:13,y:14},{kind:'stone',x:31,y:8},{kind:'stone',x:35,y:19},{kind:'crystal',x:37,y:10}
];
const RELICS=[{id:'skoglys',x:18,y:8},{id:'bekkelys',x:25,y:20},{id:'hulelys',x:33,y:18}];
const SECRETS=[{id:'stjernestein',x:34,y:9}];
const TRIAL={x:11,y:20,enemies:['kongleklo','kullvinge','fjordfnugg']};
const NIGHT_TRAIL=[{stage:0,x:7,y:17},{stage:1,x:17,y:14},{stage:2,x:23,y:10},{stage:3,x:10,y:17}];

function saveGame(show=false){if(!game.started)return;if(runtimeConfig.debugActive){if(show)toast('Debugmodus: lagring er deaktivert');return;}game.elapsed=elapsedSeconds();const data={player:game.player,team:game.team,reserve:game.reserve,seen:game.seen,caught:game.caught,quest:game.quest,bossDefeated:game.bossDefeated,endingType:game.endingType,dialogs:game.dialogs,sideQuests:game.sideQuests,nightTrail:game.nightTrail,secrets:game.secrets,trial:{...game.trial,active:false,wins:0,berriesUsed:0},relics:game.relics,inventory:game.inventory,base:game.base,gathered:game.gathered,trainers:game.trainers,elapsed:game.elapsed,best:game.best,sound:game.sound};localStorage.setItem(SAVE_KEY,JSON.stringify(data));game.lastSave=performance.now();if(show)toast('Eventyret er lagret ✓');}
function hasSave(){try{return!!JSON.parse(localStorage.getItem(SAVE_KEY)||'null');}catch{return false;}}
function normalizeUnit(u){if(!u||!C.CREATURES[u.id])return null;const level=Math.max(1,Math.floor(Number(u.level)||1)),unit={...C.makeCreature(u.id,level),...u,level,xp:Math.max(0,Math.floor(Number(u.xp)||0)),bond:Math.max(0,Math.floor(Number(u.bond)||0)),form:C.FORM_PATHS[u.form]?u.form:null,status:{guard:0,weaken:0,...u.status}};const stats=C.statsFor(unit.id,unit.level,unit.form);unit.maxHp=stats.maxHp;unit.hp=C.clamp(Number(unit.hp)||1,0,unit.maxHp);const chosen=Array.isArray(u.selectedMoves)?u.selectedMoves:null;unit.selectedMoves=chosen&&chosen.length===3&&chosen.every((id,i)=>C.availableMoveIds(unit).includes(id)&&chosen.indexOf(id)===i)?chosen:null;return unit;}
function normalizeAssignments(){const reserveIds=new Set(game.reserve.map(u=>u.id)),used=new Set();for(const key of Object.keys(BASE_DEFS)){const id=game.base.assignments[key];if(!game.base.buildings[key]||!reserveIds.has(id)||used.has(id))game.base.assignments[key]=null;else used.add(id);}}
function normalizeExpansionState(){for(const kind of Object.keys(MATERIALS))game.inventory[kind]=Math.max(0,Math.floor(Number(game.inventory[kind])||0));game.inventory.berries=Math.max(0,Math.floor(Number(game.inventory.berries)||0));for(const key of Object.keys(BASE_DEFS))game.base.buildings[key]=C.clamp(Math.floor(Number(game.base.buildings[key])||0),0,3);game.base.gardenCharge=Math.max(0,Math.floor(Number(game.base.gardenCharge)||0));for(const id of TRAINERS.map(t=>t.id))game.trainers[id]=Math.max(0,Math.floor(Number(game.trainers[id])||0));game.trainers.fjordMark=!!game.trainers.fjordMark;}
function loadGame(){try{const d=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(!d)return false;const defaults=fresh(),playerDefaults=defaults.player,dialogDefaults=defaults.dialogs,sideQuestDefaults=defaults.sideQuests,nightTrailDefaults=defaults.nightTrail,trialDefaults=defaults.trial,inventoryDefaults=defaults.inventory,baseDefaults=defaults.base,trainerDefaults=defaults.trainers;game=defaults;Object.assign(game,d,{started:true,mode:'world',battle:null,startTime:Date.now()-(d.elapsed||0)*1000});game.player={...playerDefaults,...d.player};game.player.x=C.clamp(game.player.x,TILE,(WORLD.w-1)*TILE);game.player.y=C.clamp(game.player.y,TILE,(WORLD.h-1)*TILE);game.team=(d.team||[]).map(normalizeUnit).filter(Boolean).slice(0,3);game.reserve=(d.reserve||[]).map(normalizeUnit).filter(Boolean);game.relics=d.relics||[];game.secrets=d.secrets||[];game.dialogs={...dialogDefaults,...d.dialogs};game.sideQuests={...sideQuestDefaults,...d.sideQuests};game.nightTrail={...nightTrailDefaults,...d.nightTrail};game.trial={...trialDefaults,...d.trial,active:false,wins:0,berriesUsed:0};game.inventory={...inventoryDefaults,...d.inventory};game.base={...baseDefaults,...d.base,buildings:{...baseDefaults.buildings,...d.base?.buildings},assignments:{...baseDefaults.assignments,...d.base?.assignments}};game.gathered=Array.isArray(d.gathered)?[...new Set(d.gathered.filter(id=>RESOURCE_NODES.some(n=>n.id===id)))]:[];game.trainers={...trainerDefaults,...d.trainers};normalizeExpansionState();normalizeAssignments();game.roamers=[];game.roamerSpawnAt={forest:0,cave:0,fjord:0};game.scent={activeUntil:0,cooldownUntil:0,target:null};game.particles=createAmbience();if(game.caught.includes('flammefyrsten')){game.bossDefeated=true;game.endingType='befriended';}else if(game.bossDefeated&&!game.endingType)game.endingType='defeated';game.trail=[];game.ninni={x:game.player.x-20,y:game.player.y+12};panelSignature='';bestiarySignature='';spawnRoamers();updatePanels();return true;}catch(e){console.warn('Kunne ikke laste lagring',e);return false;}}
function resetGame(){localStorage.removeItem(SAVE_KEY);game=fresh();startNew();}
function startNew(){game=fresh();game.started=true;game.mode='world';game.startTime=Date.now();game.team=[C.makeCreature('mosemurr',1)];game.seen=['mosemurr'];game.caught=['mosemurr'];spawnRoamers();hide('titleScreen');showDialog('Bestemor Tora','Ninni fant dette lille Mosemurr-vesenet under bobilen i natt. Noe har skremt naturåndene ut av skogen …','👵',()=>showDialog('Bestemor Tora','Gå østover. Bli venn med minst to forskjellige vesener, så kan dere åpne fjellporten. Roglasset fanger bare et svekket vesen.','👵',()=>{game.quest=1;game.dialogs.tora=true;updatePanels();saveGame();toast('Nytt mål: Fang minst to ulike villvesener');}));updatePanels();tone(330,.08);}
function elapsedSeconds(){return game.startTime?Math.floor((Date.now()-game.startTime)/1000):game.elapsed||0;}

function show(id){const el=$(id);el.classList.remove('hidden');if(el.classList.contains('panel-screen'))el.classList.add('visible');}
function hide(id){$(id).classList.add('hidden');$(id).classList.remove('visible');}
function visible(id){return!$(id).classList.contains('hidden')||$(id).classList.contains('visible');}
function announce(id,text){const el=$(id);el.textContent='';requestAnimationFrame(()=>{el.textContent=text;});}
function syncModeUI(){if(uiMode===game.mode)return;uiMode=game.mode;document.body.dataset.gameMode=game.mode;}
function fullscreenElement(){return document.fullscreenElement||document.webkitFullscreenElement||null;}
function syncFullscreenButton(){$('fullscreenBtn').classList.toggle('active',!!fullscreenElement());$('fullscreenBtn').title=fullscreenElement()?'Avslutt fullskjerm':'Fullskjerm';}
async function toggleFullscreen(){try{if(fullscreenElement()){const exit=document.exitFullscreen||document.webkitExitFullscreen;if(exit)await exit.call(document);return;}const root=document.documentElement,request=root.requestFullscreen||root.webkitRequestFullscreen;if(!request){toast('Safari: bruk Del → Legg til på Hjem-skjermen for fullskjerm.',3600);return;}await request.call(root,{navigationUI:'hide'});}catch{toast('Fullskjerm ble avvist. Prøv Del → Legg til på Hjem-skjermen.',3600);}finally{syncFullscreenButton();}}
function toast(text,ms=2200){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),ms);}
const SOUND_PRESETS={dialog:[.12,.04,330,.005,.025,.035,1,1,80],menu:[.16,0,620,.005,.025,.055,0,1,120],trail:[.2,.08,740,.01,.05,.1,2,1,-90,0,120,.03],hit:[.25,.08,210,.005,.06,.09,3,1,-180],critical:[.3,.08,420,.005,.08,.12,1,1,-260],enemy:[.25,.06,145,.005,.08,.13,3,1,-80],heal:[.2,.02,520,.01,.1,.18,0,1,140],capture:[.24,.03,920,.01,.12,.25,0,1,-180,0,250,.06],lose:[.25,.02,170,.02,.16,.35,3,1,-160],chime:[.2,.01,520,.005,.08,.15,0,1,80]};
async function tone(freq=440,dur=.09,type='square',vol=.035){if(!game.sound)return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;audioCtx=audioCtx||new Audio();if(audioCtx.state==='suspended')await audioCtx.resume();if(audioCtx.state&&audioCtx.state!=='running')return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur);}catch{}}
async function playPreset(params,fallback){if(!game.sound)return;try{if(typeof zzfx==='function'){let started=false;if(!zzfxX){zzfx(...params);started=true;}if(zzfxX.state==='suspended')await zzfxX.resume();if(zzfxX.state&&zzfxX.state!=='running')throw Error('AudioContext unavailable');if(!started)zzfx(...params);return;}}catch{}await tone(...fallback);}
function playSound(name){const fallback={dialog:[260,.04,'square',.018],menu:[520,.05,'square',.03],trail:[700,.06,'sine',.03],hit:[460,.09,'square',.045],critical:[690,.1,'square',.05],enemy:[150,.12,'sawtooth',.045],heal:[660,.2,'sine',.05],capture:[940,.18,'sine',.05],lose:[110,.4,'sawtooth',.045],chime:[520,.18,'square',.05]}[name]||[440,.08,'square',.03];void playPreset(SOUND_PRESETS[name]||SOUND_PRESETS.menu,fallback);}
function fanfare(){[0,120,240,360].forEach((delay,i)=>setTimeout(()=>{const p=[...SOUND_PRESETS.chime],freq=[392,523,659,784][i];p[2]=freq;void playPreset(p,[freq,.18,'square',.05]);},delay));}

let dialogDone=null;
function showDialog(speaker,text,portrait='💬',done=null){game.mode='dialog';$('speaker').textContent=speaker;$('dialogText').textContent=text;$('portrait').textContent=portrait;dialogDone=done;show('dialog');playSound('dialog');}
function advanceDialog(){if(game.mode!=='dialog')return;hide('dialog');const cb=dialogDone;dialogDone=null;game.mode='world';if(cb)setTimeout(cb,30);}

function creatureThumb(c){return`<div class="creature-icon" style="background:${c.colors[2]}"><img src="assets/creatures/${c.id}.svg" alt="Illustrasjon av ${c.name}" draggable="false" onerror="this.className='broken'"><span class="creature-fallback">${C.TYPES[c.type].icon}</span></div>`;}
function allUnits(){return[...game.team,...game.reserve];}
function unitFormLabel(u){return u?.form?C.FORM_PATHS[u.form].name:null;}
function renderBestiary(){const formSig=allUnits().map(u=>`${u.id}:${u.form||'-'}`).join(',');const signature=`${game.seen.join(',')}|${game.caught.join(',')}|${formSig}`;if(signature===bestiarySignature)return;bestiarySignature=signature;$('bestiaryList').innerHTML=Object.values(C.CREATURES).map((c,i)=>{const discovered=game.seen.includes(c.id),friend=game.caught.includes(c.id),unit=allUnits().find(u=>u.id===c.id),form=unitFormLabel(unit);if(!discovered)return`<article class="bestiary-card unknown" data-slot="${i}"><div class="bestiary-silhouette">?</div><div><b>Ukjent spor</b><small>Ikke oppdaget</small></div></article>`;return`<article class="bestiary-card ${friend?'friend':''} ${c.legendary?'legendary':''}" data-slot="${i}">${creatureThumb(c)}<div><b>${c.name}${form?` <span class="form-badge">${form}</span>`:''}</b><small>${C.TYPES[c.type].icon} ${c.type} · ${c.role} · ${c.bio}</small><small class="trait">◆ ${c.trait.name}: ${c.trait.description}</small><small class="status">${friend?'★ VENN':'◉ OPPDAGET'}</small></div></article>`;}).join('');}
function unitProgressHtml(u,scope,index){const c=C.CREATURES[u.id],available=C.availableMoveIds(u),active=C.unlockedMoveIds(u),fourth=c.moves[3],form=unitFormLabel(u);let html=`<small class="bond">♡ Vennskapsbånd ${u.bond||0}/3${form?` · ${form}`:''}</small>`;if(!c.boss&&u.level>=5&&fourth){html+=`<div class="tech-actions" aria-label="Velg tredje teknikk"><button data-tech-scope="${scope}" data-tech-index="${index}" data-tech="${c.moves[2]}" ${active.includes(c.moves[2])?'disabled':''}>${C.MOVES[c.moves[2]].name}</button><button data-tech-scope="${scope}" data-tech-index="${index}" data-tech="${fourth}" ${active.includes(fourth)?'disabled':''}>${C.MOVES[fourth].name}</button></div>`;}if(C.canChooseForm(u))html+=`<div class="form-actions"><button data-form-scope="${scope}" data-form-index="${index}" data-form="spor">🐾 Sporform</button><button data-form-scope="${scope}" data-form-index="${index}" data-form="vern">🛡️ Vernform</button></div>`;else if(!c.boss&&!form)html+=`<small>Naturform åpnes ved nivå 5 og tre vennskapsbånd.</small>`;return html;}
function unitAt(scope,index){return(scope==='team'?game.team:game.reserve)[index]||null;}
function chooseUnitMove(scope,index,moveId){const unit=unitAt(scope,index);if(!unit||!C.setThirdMove(unit,moveId))return;panelSignature='';updatePanels();saveGame();toast(`${C.CREATURES[unit.id].name} gjør ${C.MOVES[moveId].name} aktiv.`);}
function chooseUnitForm(scope,index,form){const unit=unitAt(scope,index);if(!unit||!C.chooseNatureForm(unit,form))return;panelSignature='';bestiarySignature='';updatePanels();saveGame();fanfare();const text=`${C.CREATURES[unit.id].name} finner sin ${C.FORM_PATHS[form].name}.`;announce('liveStatus',text);toast(text,3000);}
function bindProgressButtons(){document.querySelectorAll('[data-tech]').forEach(b=>b.onclick=()=>chooseUnitMove(b.dataset.techScope,Number(b.dataset.techIndex),b.dataset.tech));document.querySelectorAll('[data-form]').forEach(b=>b.onclick=()=>chooseUnitForm(b.dataset.formScope,Number(b.dataset.formIndex),b.dataset.form));}
function baseLevelTotal(){return Object.values(game.base.buildings).reduce((a,b)=>a+b,0);}
function canAfford(cost){return Object.entries(cost).every(([kind,amount])=>(game.inventory[kind]||0)>=amount);}
function costText(cost){return Object.entries(cost).map(([kind,n])=>`${MATERIALS[kind].icon}${n}`).join(' ');}
function renderBasePanel(){const total=baseLevelTotal();$('baseResources').innerHTML=Object.entries(MATERIALS).map(([kind,m])=>`<span>${m.icon} ${game.inventory[kind]||0}</span>`).join('');$('fjordUnlockText').textContent=!game.bossDefeated?'Fullfør hovedhistorien først.':total<4?`Bygg fire nivåer totalt (${total}/4).`:(game.trainers.fjordMark?'Fjordvoktermerket er vunnet. Ruten er trygg.':'Ruten er åpen. Fjordvokter Inga venter ved havet.');$('baseList').innerHTML=Object.entries(BASE_DEFS).map(([key,d])=>{const level=game.base.buildings[key],cost=d.costs[level],ready=cost&&canAfford(cost),worker=game.base.assignments[key];const options=['<option value="">Ingen bemanning</option>',...game.reserve.map(u=>`<option value="${u.id}" ${worker===u.id?'selected':''}>${C.TYPES[C.CREATURES[u.id].type].icon} ${C.CREATURES[u.id].name}</option>`)].join('');return`<article class="base-card ${ready?'ready':''}" data-building="${key}"><h3><span>${d.icon} ${d.name}</span><span>Lv.${level}/3</span></h3><p>${d.effect}</p><p>${level<3?`Neste nivå: ${costText(cost)}`:'Fullt utbygd'}</p><select class="base-worker" data-worker="${key}" aria-label="Bemann ${d.name}" ${level?'':'disabled'}>${options}</select><div class="base-actions"><button data-upgrade="${key}" ${!ready||level>=3?'disabled':''}>${level?'OPPGRADER':'BYGG'}</button></div></article>`;}).join('');document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>upgradeBuilding(b.dataset.upgrade));document.querySelectorAll('[data-worker]').forEach(s=>s.onchange=()=>assignBuilding(s.dataset.worker,s.value||null));}
function upgradeBuilding(key){const d=BASE_DEFS[key],level=game.base.buildings[key],cost=d?.costs[level];if(!cost||!canAfford(cost))return;for(const [kind,n] of Object.entries(cost))game.inventory[kind]-=n;game.base.buildings[key]++;if(key==='garden')game.inventory.berries+=game.base.buildings[key];panelSignature='';renderBasePanel();updatePanels();saveGame();fanfare();const text=`${d.name} er nå nivå ${game.base.buildings[key]}.`;announce('liveStatus',text);toast(text);}
function assignBuilding(key,id){if(!BASE_DEFS[key])return;if(id&&(!game.base.buildings[key]||!game.reserve.some(u=>u.id===id)))id=null;for(const k of Object.keys(BASE_DEFS))if(game.base.assignments[k]===id)game.base.assignments[k]=null;game.base.assignments[key]=id;renderBasePanel();saveGame();const text=id?`${C.CREATURES[id].name} bemanner ${BASE_DEFS[key].name}.`:`${BASE_DEFS[key].name} står uten bemanning.`;announce('liveStatus',text);toast(text);}
function updatePanels(){
 const area=areaAt(game.player.x);$('areaLabel').textContent=area==='camp'?'Furuly Camping':area==='forest'?'Hviskeskogen':area==='cave'?'Glødesteinshulen':'Fjordbygda';
 const caughtWild=game.caught.filter(id=>id!=='mosemurr'&&id!=='flammefyrsten').length;
 const bossFriend=game.caught.includes('flammefyrsten');
 const questText=game.bossDefeated?(bossFriend?'Historien fullført · Fjellvenn':'Historien fullført · Fjellet er reddet'):game.quest===0?'Snakk med Bestemor Tora':game.quest===1?`Fang villvesener (${Math.min(caughtWild,2)}/2)`:game.quest===2?'Finn Flammefyrsten i hulen':'Utforsk Villspor';
 const nightShort=!game.nightTrail.completed&&game.nightTrail.stage>0?`Ninnis nattspor · steg ${game.nightTrail.stage}/3`:null;
 $('questShort').textContent=nightShort||questText;
 $('seenCount').textContent=game.seen.length;$('caughtCount').textContent=game.caught.length;$('berryCount').textContent=game.inventory.berries;$('relicCount').textContent=game.relics.length;for(const kind of Object.keys(MATERIALS))$(`${kind}Count`).textContent=game.inventory[kind]||0;renderBestiary();
 const signature=[...game.team,...game.reserve].map(u=>`${u.id}:${u.level}:${u.hp}:${u.xp}:${u.bond}:${u.form}:${u.selectedMoves?.join(',')}`).join('|')+`/${game.team.map(u=>u.id).join(',')}|${JSON.stringify(game.base)}|${game.inventory.wood}:${game.inventory.crystal}:${game.inventory.herb}`;if(signature!==panelSignature){panelSignature=signature;
 $('teamList').innerHTML=game.team.map((u,i)=>{const c=C.CREATURES[u.id],active=C.unlockedMoveIds(u);return`<div class="creature-card">${creatureThumb(c)}<div><b>${i===0?'★ ':''}${c.name}${unitFormLabel(u)?` <span class="form-badge">${unitFormLabel(u)}</span>`:''}</b> · Lv.${u.level}<small>${c.bio}</small><small class="move-list">${c.role} · ${active.map(m=>C.MOVES[m].name).join(' · ')}</small><small class="trait">◆ ${c.trait.name}: ${c.trait.description}</small><div class="hpbar"><i style="width:${100*u.hp/u.maxHp}%"></i></div><small>${u.hp}/${u.maxHp} HP · ${u.xp}/${C.xpNeeded(u.level)} XP</small>${unitProgressHtml(u,'team',i)}</div><div><span class="type type-${c.type.toLowerCase()}">${c.type}</span>${i?`<button class="swap-mini" data-leader="${i}">LEDER</button>`:''}</div></div>`}).join('')||'<p>Ingen vesener i flokken.</p>';
 $('reserveList').innerHTML=game.reserve.map((u,i)=>{const c=C.CREATURES[u.id];return`<div class="creature-card">${creatureThumb(c)}<div><b>${c.name}${unitFormLabel(u)?` <span class="form-badge">${unitFormLabel(u)}</span>`:''}</b> · Lv.${u.level}<small>${u.hp}/${u.maxHp} HP · venter ved leiren</small>${unitProgressHtml(u,'reserve',i)}</div><button class="swap-mini" data-reserve="${i}">BYTT INN</button></div>`}).join('')||'<p class="panel-hint">Ingen vesener venter ved leiren ennå.</p>';
 document.querySelectorAll('[data-leader]').forEach(b=>b.onclick=()=>setLeader(Number(b.dataset.leader)));document.querySelectorAll('[data-reserve]').forEach(b=>b.onclick=()=>bringReserve(Number(b.dataset.reserve)));bindProgressButtons();refreshCampFriends();renderBasePanel();}
 const quests=[['Møt Bestemor Tora',game.quest>0],['Bli venn med to villvesener',caughtWild>=2],['Åpne fjellporten',game.quest>=2],['Hovedhistorien: Stans Flammefyrsten',game.bossDefeated],[`Valgfritt: Finn tre glødespor (${game.relics.length}/3)`,game.relics.length===3]];const nightLabels=['Valgfritt: Undersøk Ninnis spor ved campingen','Ninnis nattspor: Følg potesporene inn i skogen','Ninnis nattspor: Undersøk lyssporet i lysningen','Ninnis nattspor: Gå tilbake til campingplassen'];quests.push([game.nightTrail.completed?'Ninnis nattspor: Spormerket funnet':nightLabels[game.nightTrail.stage],game.nightTrail.completed,game.nightTrail.stage>0]);quests.push([game.sideQuests.loke==='done'?'Sideoppdrag: Fjordfnuggets blå dun':'Sideoppdrag: Finn og bli venn med Fjordfnugg',game.sideQuests.loke==='done',game.sideQuests.loke==='active']);quests.push([game.sideQuests.siv==='done'?'Sideoppdrag: Naturkretsen er samlet':'Sideoppdrag: Samle ild, vekst og vann',game.sideQuests.siv==='done',game.sideQuests.siv==='active']);quests.push([game.secrets.includes('stjernestein')?'Hemmelighet: Stjernesteinen funnet':'Valgfritt: Følg det blå glimtet i hulen',game.secrets.includes('stjernestein'),false]);quests.push([game.trial.completed?`Postgame: Sporprøven fullført · rekord ${game.trial.bestBerries??'–'} villbær`:'Postgame: Sporprøven ved leiren',game.trial.completed,game.bossDefeated&&!game.trial.completed]);if(game.bossDefeated)quests.push([bossFriend?'Flammefyrsten ble en fjellvenn':'Valgfritt: Vennskapsprøven ved fjellets hjerte',bossFriend]);
 const baseTotal=baseLevelTotal();quests.push([`Basecamp: Bygg fire nivåer (${Math.min(baseTotal,4)}/4)`,baseTotal>=4,game.bossDefeated]);quests.push([game.trainers.fjordMark?'Fjordbygda: Fjordvoktermerket vunnet':'Fjordbygda: Utfordre tre stifinnere',game.trainers.fjordMark,game.bossDefeated&&baseTotal>=4]);
 $('questList').innerHTML=quests.map(([q,d,a],i)=>`<div class="quest ${d?'done':(a||(!d&&quests.slice(0,i).every(x=>x[1]))?'active':'')}">${d?'✓':'○'} ${q}</div>`).join('');
}
function setLeader(i){if(i<=0||i>=game.team.length)return;game.team.unshift(game.team.splice(i,1)[0]);updatePanels();saveGame();toast(`${C.CREATURES[game.team[0].id].name} leder flokken.`);}
function bringReserve(i){if(i<0||i>=game.reserve.length||!game.team.length)return;const incoming=game.reserve[i],outgoing=game.team[0];game.reserve.splice(i,1,outgoing);game.team[0]=incoming;normalizeAssignments();panelSignature='';updatePanels();saveGame();toast(`${C.CREATURES[incoming.id].name} blir med. ${C.CREATURES[outgoing.id].name} hviler ved leiren.`);}
function openPanel(id){if(game.mode!=='world')return;hide('teamPanel');hide('questPanel');hide('basePanel');show(id);if(id==='basePanel')renderBasePanel();game.mode='panel';playSound('menu');}
function closePanels(){hide('teamPanel');hide('questPanel');hide('basePanel');if(game.mode==='panel')game.mode='world';}

function hash(x,y){let h=(x*374761393+y*668265263)^0x5bd1e995;h=(h^(h>>13))*1274126177;return(h^(h>>16))>>>0;}
function areaAt(px){const tx=px/TILE;return tx<14?'camp':tx<29?'forest':tx<42?'cave':'fjord';}
function blocked(px,py){const x=Math.floor(px/TILE),y=Math.floor(py/TILE);if(x<1||y<1||x>=WORLD.w-1||y>=WORLD.h-1)return true;
 if(x===29&&y>=1&&y<=26&&!(y>=13&&y<=15))return true;
 if(x===42&&y>=1&&y<=26&&!(y>=13&&y<=15))return true;
 if(x>=14&&x<29){const path=y>=13&&y<=15;const clear=(x>20&&x<25&&y>7&&y<12);if(!path&&!clear&&hash(x,y)%5===0)return true;}
 if(x>=30&&x<42){if(y<6||y>22)return true;if((y===7||y===21)&&x>31&&hash(x,y)%2===0)return true;}
 if(x>=43){const path=y>=13&&y<=15,shore=y>=7&&y<=21;if(!shore)return true;if(!path&&hash(x,y)%8===0)return true;}
 if(x<14){if((x===2||x===11)&&y>4&&y<10)return true;}
 for(const p of PROPS){if(['tent','camper','stone'].includes(p.kind)&&Math.abs(px-(p.x+.5)*TILE)<22&&Math.abs(py-(p.y+.5)*TILE)<19)return true;}
 for(const [key,b] of Object.entries(BASE_DEFS))if(game.base.buildings[key]&&Math.abs(px-(b.x+.5)*TILE)<21&&Math.abs(py-(b.y+.5)*TILE)<19)return true;
 return false;
}
function createAmbience(){return Array.from({length:24},(_,i)=>({x:(i*173+61)%960,y:(i*97+43)%540,phase:i*.73,speed:.3+(i%5)*.08,size:1.5+(i%4)*.65}));}
function roamerBlocked(px,py){const r=18;return blocked(px,py)||blocked(px-r,py)||blocked(px+r,py)||blocked(px,py-r)||blocked(px,py+r)||blocked(px-r,py-r)||blocked(px+r,py-r)||blocked(px-r,py+r)||blocked(px+r,py+r);}
function safeRoamerPosition(x,y){if(roamerBlocked(x,y)||Math.hypot(game.player.x-x,game.player.y-y)<80)return false;for(const n of [...NPCS,...TRAINERS])if(Math.hypot(n.x-x,n.y-y)<76)return false;for(const p of [...RELICS,...SECRETS,...RESOURCE_NODES])if(Math.hypot((p.x+.5)*TILE-x,(p.y+.5)*TILE-y)<76)return false;for(const p of NIGHT_TRAIL)if(Math.hypot((p.x+.5)*TILE-x,(p.y+.5)*TILE-y)<76)return false;if(Math.hypot((TRIAL.x+.5)*TILE-x,(TRIAL.y+.5)*TILE-y)<76)return false;return true;}
function spawnRoamers(area=null,now=performance.now()){if(!runtimeConfig.roamerEnabled||!game.started)return;for(const [zoneName,zone] of Object.entries(ROAMER_ZONES)){if(area&&zoneName!==area)continue;if(now<(game.roamerSpawnAt[zoneName]||0))continue;for(let i=0;i<zone.max;i++){const token=`${zoneName}-${i}`;if(game.roamers.some(r=>r.token===token))continue;const [tx,ty]=zone.spots[i],id=zone.ids[(i+game.caught.length)%zone.ids.length],x=tx*TILE,y=ty*TILE;if(!safeRoamerPosition(x,y))continue;game.roamers.push({token,area:zoneName,id,x,y,homeX:x,homeY:y,angle:(i+1)*1.7,turnAt:now+900+i*370,engaged:false});}}}
function forceRoamer(id='gnistrev',x=18,y=12){const area=areaAt(x*TILE),token=`forced-${performance.now()}`;const r={token,area,id,x:x*TILE,y:y*TILE,homeX:x*TILE,homeY:y*TILE,angle:0,turnAt:0,engaged:false};game.roamers.push(r);return r;}
function nearestRoamer(maxDistance=Infinity){const area=areaAt(game.player.x);let best=null,distance=maxDistance;for(const r of game.roamers){if(r.engaged||r.area!==area)continue;const d=Math.hypot(game.player.x-r.x,game.player.y-r.y);if(d<distance){best=r;distance=d;}}return best?{roamer:best,distance}:null;}
function showEncounterBanner(id){const c=C.CREATURES[id],text=`Et levende spor! ${c.name}`,$el=$('encounterBanner');$el.innerHTML=`${C.TYPES[c.type].icon} Et levende spor!<strong>${c.name}</strong>`;show('encounterBanner');announce('alertStatus',text);}
function hideScent(){game.scent.activeUntil=0;game.scent.target=null;hide('scentHud');}
function engageRoamer(r){if(!r||r.engaged||game.mode!=='world'||!game.team.some(u=>u.hp>0))return false;r.engaged=true;game.mode='encounter';game.roamers=game.roamers.filter(x=>x!==r);game.roamerSpawnAt[r.area]=Infinity;hideScent();showEncounterBanner(r.id);playSound('trail');setTimeout(()=>{hide('encounterBanner');if(game.mode==='encounter')startBattle(r.id,Math.min(4,1+Math.floor((game.caught.length-1)/2)),false,false,r.area);},420);return true;}
function updateRoamers(dt,now=performance.now()){let standardCount=0;for(const r of game.roamers)if(!r.token.startsWith('forced-'))standardCount++;const targetCount=Object.values(ROAMER_ZONES).reduce((n,z)=>n+z.max,0);if(standardCount<targetCount)spawnRoamers(null,now);if(game.mode!=='world')return;for(const r of game.roamers){const pd=Math.hypot(game.player.x-r.x,game.player.y-r.y);if(!reducedMotion){if(now>=r.turnAt){r.angle+=(Math.random()-.5)*2.4;r.turnAt=now+1000+Math.random()*1800;}if(pd<72)r.angle=Math.atan2(r.y-game.player.y,r.x-game.player.x);const homeDistance=Math.hypot(r.x-r.homeX,r.y-r.homeY);if(homeDistance>48)r.angle=Math.atan2(r.homeY-r.y,r.homeX-r.x);const speed=pd<72?20:10,nx=r.x+Math.cos(r.angle)*speed*dt,ny=r.y+Math.sin(r.angle)*speed*dt;if(!roamerBlocked(nx,ny)){r.x=nx;r.y=ny;}else{r.angle+=Math.PI*.7;r.turnAt=now+500;}}if(pd<24){engageRoamer(r);break;}}}
function directionName(dx,dy){if(Math.abs(dx)>Math.abs(dy))return dx>0?'øst':'vest';return dy>0?'sør':'nord';}
function baseWorkerBonus(key){const id=game.base.assignments[key],def=BASE_DEFS[key];return!!game.base.buildings[key]&&!!id&&C.CREATURES[id]?.type===def.type;}
function activateScent(now=performance.now()){if(game.mode!=='world')return false;if(now<game.scent.cooldownUntil){toast('Ninni må lytte et øyeblikk til …');return false;}const found=nearestRoamer(),level=game.base.buildings.workshop||0,cooldown=Math.max(4200,8000-level*700-(baseWorkerBonus('workshop')?600:0));game.scent.cooldownUntil=now+cooldown;playSound('trail');if(!found){hideScent();toast('Ninni snuser, men finner ingen ferske spor her.');return false;}const r=found.roamer,c=C.CREATURES[r.id],direction=directionName(r.x-game.player.x,r.y-game.player.y),text=`Ninni finner et ${C.TYPES[c.type].icon}-spor mot ${direction}`;game.scent.target=r.token;game.scent.activeUntil=now+6000;$('scentHud').textContent=`🐶 ${text}`;show('scentHud');announce('liveStatus',text);return true;}
function refreshCampFriends(){const leader=game.team[0]?.id,ids=[];for(const list of [game.reserve,game.team])for(let i=list===game.team?1:0;i<list.length;i++){const id=list[i]?.id;if(id&&!ids.includes(id))ids.push(id);}for(const id of game.caught)if(id!==leader&&!ids.includes(id))ids.push(id);campFriendCache=ids.slice(0,CAMP_FRIEND_SLOTS.length).map((id,i)=>({id,x:CAMP_FRIEND_SLOTS[i][0]*TILE,y:CAMP_FRIEND_SLOTS[i][1]*TILE}));}
function campFriends(){return areaAt(game.player.x)==='camp'?campFriendCache:[];}
function nearestCampFriend(){let best=null,distance=48;for(const f of campFriends()){const d=Math.hypot(game.player.x-f.x,game.player.y-f.y);if(d<distance){best=f;distance=d;}}return best;}
function tryMove(dx,dy,dt){if(game.mode!=='world')return;const p=game.player,dist=runtimeConfig.playerSpeed*dt;let nx=p.x+dx*dist,ny=p.y+dy*dist;const r=10;
 if(!blocked(nx-r,p.y)&&!blocked(nx+r,p.y))p.x=nx;if(!blocked(p.x,ny-r)&&!blocked(p.x,ny+r))p.y=ny;
 if(dx||dy){p.dir=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');game.trail.push({x:p.x,y:p.y});if(game.trail.length>18)game.trail.shift();const old={x:game.ninni.x,y:game.ninni.y};const target=game.trail[Math.max(0,game.trail.length-13)];if(target){game.ninni.x+=(target.x-game.ninni.x)*Math.min(1,dt*8);game.ninni.y+=(target.y-game.ninni.y)*Math.min(1,dt*8);}const moved=Math.hypot(p.x-old.x,p.y-old.y);game.moved+=dist;game.encounterCooldown-=dist;checkAreaGate();if(game.encounterCooldown<=0)maybeEncounter();}
}
function checkAreaGate(){if(game.player.x>28.7*TILE&&game.caught.length-1<2){game.player.x=28.55*TILE;showDialog('Ninni','Voff! Fjellporten svarer ikke ennå. Vi trenger vennskapet til minst to villvesener.','🐶');}
 if(game.player.x>29.2*TILE&&game.quest<2&&game.caught.length-1>=2){game.quest=2;toast('Fjellporten åpnet seg!');fanfare();updatePanels();saveGame();}
 if(game.player.x>41.7*TILE&&(!game.bossDefeated||baseLevelTotal()<4)){game.player.x=41.55*TILE;if(game.bossDefeated)showDialog('Ninni',`Vinden fra Fjordbygda er for sterk. Bygg fire nivåer ved Basecamp (${baseLevelTotal()}/4).`,'🐶');}
 if(game.player.x>42.2*TILE&&game.bossDefeated&&baseLevelTotal()>=4&&!game.dialogs.fjordGate){game.dialogs.fjordGate=true;fanfare();updatePanels();saveGame();toast('Ny rute: Fjordbygda');}
}
function maybeEncounter(){game.encounterCooldown=runtimeConfig.encounterMin+Math.random()*runtimeConfig.encounterRange;const area=areaAt(game.player.x);if(nearestRoamer(180)||!encounters[area]||Math.random()>runtimeConfig.encounterChance||game.mode!=='world')return;const pool=encounters[area],id=pool[Math.floor(Math.random()*pool.length)];runtimeConfig.fallbackEncounters++;startBattle(id,Math.min(4,1+Math.floor((game.caught.length-1)/2)),false);}
function nearestNPC(){let best=null,bd=58;for(const n of NPCS){const d=Math.hypot(game.player.x-n.x,game.player.y-n.y);if(d<bd){best=n;bd=d;}}return best;}
function nearestTrainer(){let best=null,bd=58;for(const n of TRAINERS){const d=Math.hypot(game.player.x-n.x,game.player.y-n.y);if(d<bd){best=n;bd=d;}}return best;}
function nearestResource(){return RESOURCE_NODES.find(n=>!game.gathered.includes(n.id)&&Math.hypot(game.player.x-(n.x+.5)*TILE,game.player.y-(n.y+.5)*TILE)<54)||null;}
function nearestBuilding(){for(const [key,b] of Object.entries(BASE_DEFS))if(Math.hypot(game.player.x-(b.x+.5)*TILE,game.player.y-(b.y+.5)*TILE)<58)return key;return null;}
function collectResource(node){if(!node||game.gathered.includes(node.id))return;game.gathered.push(node.id);game.inventory[node.kind]+=node.amount;panelSignature='';updatePanels();saveGame();playSound('chime');const m=MATERIALS[node.kind],text=`Ninni fant ${node.amount} ${m.name.toLowerCase()}.`;announce('liveStatus',text);toast(`${m.icon} ${text}`);}
function talkTrainer(trainer){if(trainer.guardian&&(!game.trainers.runa||!game.trainers.aksel)){showDialog(trainer.name,'Fjordvokterprøven åpnes når både Runa og Aksel har registrert en seier mot flokken din.',trainer.icon);return;}const wins=game.trainers[trainer.id]||0;showDialog(trainer.name,wins?`Vil dere prøve en ny treningskamp mot ${C.CREATURES[trainer.enemy].name}?`:`Fjordstien formes av vennskap og strategi. Vis meg hvordan flokken samarbeider med ${C.CREATURES[trainer.enemy].name}.`,trainer.icon,()=>startTrainerBattle(trainer));}
function currentNightTrailPoint(){if(game.nightTrail.completed)return null;return NIGHT_TRAIL.find(p=>p.stage===game.nightTrail.stage)||null;}
function advanceNightTrail(){const stage=game.nightTrail.stage;if(game.nightTrail.completed)return;if(stage===0){game.nightTrail.stage=1;updatePanels();saveGame();showDialog('Ninni','Voff! Mellom bobilen og leirbålet ligger fremmede potespor. De lukter regn, sot og skog – og fortsetter østover.','🐶');return;}if(stage===1){game.nightTrail.stage=2;updatePanels();saveGame();showDialog('Ninni','Sporene krysser stien, men Ninni finner fersk sot på en knekt fururot. Noe venter ved Skogvokter Sivs lysning.','🐶');return;}if(stage===2){showDialog('Ninni','En Kullvinge vokter et ravfarget spormerke. Ninni stiller seg foran flokken – denne gangen ser hun angrepet komme.','🐶',()=>{startBattle('kullvinge',3,false);game.battle.nightTrailBattle=true;game.battle.log='Ninnis nattspor: Kullvinge vokter spormerket.';renderBattleUI();});return;}if(stage===3&&!game.nightTrail.rewarded){game.nightTrail.completed=true;game.nightTrail.rewarded=true;game.inventory.berries+=4;const active=game.team[0];if(active)C.gainXp(active,42);fanfare();updatePanels();saveGame();showDialog('Ninni','Ninni legger spormerket ved leirbålet. Hun får fire villbær, og flokklederen får 42 XP. Nå kjenner hun igjen tegnene hun bruker når hun varsler flokken i kamp.','🐶');}}
function finishNightTrailBattle(){if(game.nightTrail.completed||game.nightTrail.stage!==2)return;game.nightTrail.stage=3;updatePanels();saveGame();showDialog('Ninni','Kullvinge slipper spormerket og flyr fredelig opp i trekronene. Ninni snuser mot vest: Merket hører hjemme ved campingplassen.','🐶');}
function interact(){if(game.mode==='dialog')return advanceDialog();if(game.mode==='battle'||game.mode==='ending')return;if(game.mode==='panel')return closePanels();if(game.mode!=='world')return;
 const trainer=nearestTrainer();if(trainer){talkTrainer(trainer);return;}
 const nightPoint=currentNightTrailPoint();if(nightPoint&&Math.hypot(game.player.x-(nightPoint.x+.5)*TILE,game.player.y-(nightPoint.y+.5)*TILE)<58){advanceNightTrail();return;}
 const relic=RELICS.find(r=>!game.relics.includes(r.id)&&Math.hypot(game.player.x-(r.x+.5)*TILE,game.player.y-(r.y+.5)*TILE)<58);if(relic){collectRelic(relic);return;}
 const secret=SECRETS.find(s=>!game.secrets.includes(s.id)&&Math.hypot(game.player.x-(s.x+.5)*TILE,game.player.y-(s.y+.5)*TILE)<58);if(secret){collectSecret(secret);return;}
 const n=nearestNPC();if(n){talkNPC(n);return;}
 const resource=nearestResource();if(resource){collectResource(resource);return;}
 const building=nearestBuilding();if(building){openPanel('basePanel');return;}
 if(game.bossDefeated&&Math.hypot(game.player.x-(TRIAL.x+.5)*TILE,game.player.y-(TRIAL.y+.5)*TILE)<58){showDialog('Sporsteinen',(game.trial.completed?'Sporprøven våkner igjen. Tre kamper, ingen hvile mellom rundene. To villbær venter om flokken står løpet ut.':'Tre naturspor våkner i steinen. Overlev tre kamper uten hvile og vinn fem villbær. Roglasset kan brukes til å avbryte.')+(game.trial.bestBerries==null?'':` Rekord: ${game.trial.bestBerries} brukte villbær.`),'◆',startTrial);return;}
 const fire=PROPS.find(p=>p.kind==='fire');if(Math.hypot(game.player.x-(fire.x+.5)*TILE,game.player.y-(fire.y+.5)*TILE)<62){healTeam();showDialog('Leirbålet','Flokken hviler ved varmen. Alle får full energi.','🔥',()=>saveGame(true));return;}
 if(game.player.x>36*TILE&&game.player.x<42*TILE&&game.player.y>9*TILE&&game.player.y<19*TILE){if(game.caught.includes('flammefyrsten')){showDialog('Flammefyrsten','Fjellvokteren senker hodet mot Ninni. Glørne er varme, men fredelige.','🔥');return;}if(game.caught.length-1<2){toast('Flammefyrsten er for mektig. Finn flere venner først.');return;}startBattle('flammefyrsten',4,true,game.bossDefeated);return;}
 const roamer=nearestRoamer(46);if(roamer){engageRoamer(roamer.roamer);return;}
 const friend=nearestCampFriend();if(friend){showDialog(C.CREATURES[friend.id].name,CAMP_LINES[friend.id]||'Vennen hviler trygt ved campingplassen.',C.TYPES[C.CREATURES[friend.id].type].icon);return;}
 activateScent();
}
function collectRelic(relic){game.relics.push(relic.id);game.inventory.berries++;const complete=game.relics.length===3,active=game.team.find(u=>u.hp>0);if(active)C.gainXp(active,12);fanfare();updatePanels();saveGame();showDialog('Glødesporet',complete?'Alle tre sporene synger sammen. Roglasset blir sterkere, og Ninni finner tre ekstra villbær!':'Et gammelt lys fester seg i Roglasset. Fangstsansen blir litt sterkere. Du finner også et villbær.','✦',()=>{if(complete){game.inventory.berries+=3;updatePanels();saveGame();toast('Ninnis sporsans er fulladet!');}});}
function collectSecret(secret){if(game.secrets.includes(secret.id))return;game.secrets.push(secret.id);game.inventory.berries+=3;const active=game.team[0],before=active?.level||0;if(active)C.gainXp(active,30);const learned=before<3&&active?.level>=3?` ${C.CREATURES[active.id].name} lærer ${C.MOVES[C.CREATURES[active.id].moves[2]].name}!`:'';fanfare();updatePanels();saveGame();showDialog('Stjernesteinen',`Bak en sprekk Ninni oppdaget ligger et kaldt blått stjernelys. Flokken får 30 XP og tre villbær.${learned}`,'✧');}
function startTrial(){if(game.trial.active)return;game.trial.active=true;game.trial.wins=0;game.trial.berriesUsed=0;game.trial.runs++;for(const u of game.team)u.status={guard:0,weaken:0};startTrialRound();}
function startTrialRound(){const round=game.trial.wins,id=TRIAL.enemies[round];startBattle(id,3+round,false);game.battle.trial=true;game.battle.log=`Sporprøven ${round+1}/3: ${C.CREATURES[id].name}.${game.team.some(u=>u.id==='flammefyrsten')?' Flammefyrsten svarer med et stolt vingeslag.':''}`;renderBattleUI();}
function advanceTrial(){hide('battleUI');game.battle=null;if(game.trial.wins>=3){const first=!game.trial.completed,reward=first?5:2,used=game.trial.berriesUsed,newRecord=game.trial.bestBerries==null||used<game.trial.bestBerries;if(newRecord)game.trial.bestBerries=used;game.trial.active=false;game.trial.completed=true;game.inventory.berries+=reward;game.mode='world';fanfare();updatePanels();saveGame();showDialog('Sporprøven',`Flokken holdt sammen gjennom alle tre sporene med ${used} brukte villbær. Ninni finner ${reward} villbær ved steinen${first?' og et nytt merke føres i Reisedagboken':''}.${newRecord?' Ny rekord!':''}`,'◆');return;}game.mode='world';setTimeout(startTrialRound,260);}
function abortTrial(){if(!game.trial.active)return;hide('battleUI');game.battle=null;game.trial.active=false;game.trial.wins=0;game.mode='world';saveGame();toast('Sporprøven ble avsluttet. Fremgangen i eventyret er trygg.');}
function sideQuestReady(id){if(id==='loke')return game.caught.includes('fjordfnugg');if(id==='siv')return['ILD','VEKST','VANN'].every(type=>game.caught.some(cid=>C.CREATURES[cid]?.type===type));return false;}
function completeSideQuest(id,n){if(game.sideQuests[id]==='done')return;game.sideQuests[id]='done';const active=game.team[0],before=active?.level||0,reward=id==='loke'?{berries:3,xp:24}:{berries:2,xp:38};game.inventory.berries+=reward.berries;const levels=active?C.gainXp(active,reward.xp):[];const unlocked=before<3&&active?.level>=3?` ${C.CREATURES[active.id].name} lærer ${C.MOVES[C.CREATURES[active.id].moves[2]].name}!`:'';updatePanels();saveGame();fanfare();showDialog(n.name,id==='loke'?`Du fant Fjordfnugg-sporet! Ninni får ${reward.berries} villbær, og flokklederen får ${reward.xp} XP.${unlocked}`:`Ild, vekst og vann går sammen i en naturkrets. Flokklederen får ${reward.xp} XP og ${reward.berries} villbær.${unlocked}`,n.icon);}
function handleSideQuest(n){const state=game.sideQuests[n.id];if(!state||state==='done')return false;if(sideQuestReady(n.id)){completeSideQuest(n.id,n);return true;}if(state==='available'){game.sideQuests[n.id]='active';updatePanels();saveGame();showDialog(n.name,n.id==='loke'?'Et Fjordfnugg mistet et blått dun øst i skogen. Kan Ninni finne vesenet og bli venn med det? Jeg har tre villbær til den som lykkes.':'Skogen trenger balanse. Bli venn med minst ett ild-, vekst- og vannvesen, så lærer flokken å kjempe som en naturkrets.',n.icon);return true;}showDialog(n.name,n.id==='loke'?'Fjordfnugg følger bekken og vinden. Se etter det blå sporet i den østlige skogen.':'Naturkretsen mangler fortsatt en type. Sjekk Sporboka: ild, vekst og vann må alle være venner.',n.icon);return true;}
function talkNPC(n){const bossFriend=game.caught.includes('flammefyrsten');if(n.id!=='tora'&&handleSideQuest(n))return;if(n.id==='tora'){showDialog(n.name,bossFriend?'Ninni kom hjem med selveste fjellvokteren i hælene! Flammefyrsten valgte dere – det vennskapet skal leiren huske.':game.bossDefeated?'Dere stilnet fjellets sinne. Fyrsten vokter fortsatt hjertet der inne, og Ninni kan lede dere tilbake når dere er klare.':game.quest===0?'Ninni fant Mosemurr ved bobilen. Ta vare på hverandre og følg sporene østover.':'Roglasset virker best når vesenet har lite energi igjen. Leirbålet helbreder hele flokken.',n.icon);}
 if(n.id==='loke')showDialog(n.name,bossFriend?'Jeg hørte vingeslag over hele campingen! Tenk at Flammefyrsten faktisk følger flokken deres.':game.bossDefeated?'Flammene over fjellet er rolige nå. Jeg visste Ninni kunne finne veien hjem igjen!':game.dialogs.loke?'Jeg så et blått fjordfnugg mellom tretoppene!':'Hør! Skogen lager sin egen melodi. Trykk F for å se flokken din.',n.icon,()=>{game.dialogs.loke=true;saveGame();});
 if(n.id==='siv')showDialog(n.name,bossFriend?'Fjellet valgte vennskap fremfor frykt. Fjordbygda har åpnet tre nye spor i Sporboka.':game.bossDefeated?'Hovedhistorien er fullført, men skogen har fortsatt venner dere ikke har møtt.':'Ild slår vekst, vekst slår vann, og vann slår ild. Ingen type er alltid sterkest.',n.icon,()=>{game.dialogs.siv=true;saveGame();});
}
function healTeam(){for(const u of game.team)u.hp=u.maxHp;updatePanels();playSound('heal');}

function intentHint(enemy,target,moveId){const move=C.MOVES[moveId],type=C.TYPES[move.type].icon;if(move.effect==='heal')return`Varsel: ${C.CREATURES[enemy.id].name} samler krefter for å helbrede.`;if(move.effect==='guard')return`Varsel: ${C.CREATURES[enemy.id].name} gjør seg klar til å skjerme seg.`;if(move.effect==='weaken')return`Varsel: ${C.CREATURES[enemy.id].name} sprer et svekkende ${type}-spor.`;const mult=C.typeMultiplier(move.type,C.CREATURES[target.id].type);if(mult>1)return`Varsel: Et fordelaktig ${type}-angrep lades.`;if(move.power>=15)return`Varsel: Et tungt ${type}-angrep er på vei.`;return`Varsel: ${C.CREATURES[enemy.id].name} følger bevegelsene deres.`;}
function prepareEnemyIntent(){const b=game.battle;if(!b)return;const target=game.team[b.active];b.intent=C.chooseEnemyMove(b.enemy,target,Math.random());b.intentHint=intentHint(b.enemy,target,b.intent);}
function startBattle(id,level=1,boss=false,rematch=false,roamerArea=null){if(game.mode==='battle')return;hide('encounterBanner');hideScent();const enemy=C.makeCreature(id,level),isBoss=boss||!!C.CREATURES[id].boss;if(isBoss){enemy.maxHp+=28;enemy.hp=enemy.maxHp;}game.seen=[...new Set([...game.seen,id])];game.battle={enemy,active:Math.max(0,game.team.findIndex(u=>u.hp>0)),boss:isBoss,rematch,roamerArea,locked:false,round:0,fx:{kind:'enter',target:'enemy',until:performance.now()+420},log:rematch?'Flammefyrsten venter ved fjellets hjerte. Vennskapsprøven begynner på nytt!':`${boss?'Fjellet rister! ':'Et vilt '}${C.CREATURES[id].name} viser seg!`};game.mode='battle';prepareEnemyIntent();show('battleUI');closePanels();renderBattleUI();tone(boss?110:220,.25,'sawtooth',.05);updatePanels();}
function startTrainerBattle(trainer){startBattle(trainer.enemy,trainer.level,false,false,null);game.battle.trainerId=trainer.id;game.battle.log=`${trainer.name} utfordrer flokken med ${C.CREATURES[trainer.enemy].name}. Roglasset hviler i trenerkamper.`;renderBattleUI();}
function captureOdds(unit){const workshop=game.base.buildings.workshop||0,staff=baseWorkerBonus('workshop')?.02:0;return C.clamp(C.captureChance(unit)+game.relics.length*.05+workshop*.01+staff,0,.95);}
function currentBossFriendship(){const b=game.battle;return b?.boss?C.bossFriendshipState(b.enemy,game.relics.length,game.caught.includes('flammefyrsten')):'not-boss';}
function renderBattleUI(){const b=game.battle;if(!b)return;const p=game.team[b.active],e=b.enemy,pc=C.CREATURES[p.id],ec=C.CREATURES[e.id];const ps=[p.status.guard?'🛡️ Skjold':'',p.status.weaken?'⬇️ Svekket':''].filter(Boolean).join(' · '),es=[e.status.guard?'🛡️ Skjold':'',e.status.weaken?'⬇️ Svekket':''].filter(Boolean).join(' · ');$('battleStatus').innerHTML=`<div><b>${pc.name}${unitFormLabel(p)?` · ${unitFormLabel(p)}`:''}</b> Lv.${p.level}<div class="hpbar"><i style="width:${100*p.hp/p.maxHp}%"></i></div>${p.hp}/${p.maxHp} HP <small>${ps}</small></div><div><b>${ec.name}</b> Lv.${e.level}<div class="hpbar"><i style="width:${100*e.hp/e.maxHp}%"></i></div>${e.hp}/${e.maxHp} HP <small>${es}</small></div>`;$('battleLog').textContent=b.log+(!b.locked&&b.intentHint?` · ⚠ ${b.intentHint}`:'');const unlocked=C.unlockedMoveIds(p);for(let i=0;i<3;i++){const btn=$(`move${i+1}Btn`),moveId=unlocked[i]||pc.moves[i],move=C.MOVES[moveId],open=!!unlocked[i];btn.textContent=open?`${C.TYPES[move.type].icon} ${move.name}`:`🔒 ${move.name} Lv.3`;btn.disabled=b.locked||!open;}const bossState=currentBossFriendship(),capture=$('captureBtn'),bossLabels={'missing-relics':'✦ FINN 3 SPOR',weaken:'🔥 SVEKK MER',ready:'🧿 FJELLROGLAS',already:'★ ALLEREDE VENN'};if(b.trial){capture.disabled=b.locked;capture.textContent='↩ AVBRYT PRØVE';capture.dataset.state='trial';capture.classList.remove('ready');}else if(b.trainerId){capture.disabled=true;capture.textContent='⚑ TRENERKAMP';capture.dataset.state='trainer';capture.classList.remove('ready');}else{capture.disabled=b.locked||(b.boss&&bossState!=='ready');capture.textContent=b.boss?bossLabels[bossState]:`🧿 ROGLAS ${Math.round(captureOdds(e)*100)}%`;capture.dataset.state=b.boss?bossState:'wild';capture.classList.toggle('ready',bossState==='ready');}$('itemBtn').textContent=`🫐 VILLBÆR ×${game.inventory.berries}`;$('itemBtn').disabled=b.locked||game.inventory.berries<1||p.hp>=p.maxHp;$('switchBtn').disabled=b.locked||game.team.filter(u=>u.hp>0).length<2;}
function setBattleLog(text){if(!game.battle)return;game.battle.log=text;$('battleLog').textContent=text;}
function playerMove(moveIndex){const b=game.battle;if(!b||b.locked)return;const unit=game.team[b.active],move=C.unlockedMoveIds(unit)[moveIndex];if(!move)return;b.locked=true;const r=C.applyMove(unit,b.enemy,move,.82+Math.random()*.18);b.fx={kind:r.mult>1?'burst':'hit',target:'enemy',until:performance.now()+420};playSound(r.mult>1?'critical':'hit');setBattleLog(`${C.CREATURES[unit.id].name} brukte ${r.move.name}! ${r.mult>1?'Det traff ekstra hardt! ':r.mult<1?'Ikke særlig effektivt. ':''}−${r.damage} HP`);renderBattleUI();setTimeout(()=>{if(b.enemy.hp<=0)return winBattle();enemyTurn();},650);}
function enemyTurn(){const b=game.battle;if(!b)return;const enemy=b.enemy,unit=game.team[b.active],available=C.unlockedMoveIds(enemy);const move=available.includes(b.intent)?b.intent:C.chooseEnemyMove(enemy,unit,Math.random());const r=C.applyMove(enemy,unit,move,.78+Math.random()*.19);b.fx={kind:r.mult>1?'burst':'hit',target:'player',until:performance.now()+420};playSound('enemy');setBattleLog(`${C.CREATURES[enemy.id].name} følger varslet og bruker ${r.move.name}. −${r.damage} HP`);C.tickStatus(enemy);C.tickStatus(unit);renderBattleUI();setTimeout(()=>{if(unit.hp<=0){const next=game.team.findIndex((u,i)=>i!==b.active&&u.hp>0);if(next<0)return loseBattle();b.active=next;setBattleLog(`${C.CREATURES[unit.id].name} må hvile. ${C.CREATURES[game.team[next].id].name} tar over!`);}b.round++;b.locked=false;prepareEnemyIntent();renderBattleUI();},650);}
function attemptCapture(){const b=game.battle;if(!b||b.locked||b.trainerId)return;if(b.trial){abortTrial();return;}if(b.boss){const state=currentBossFriendship();if(state!=='ready'){setBattleLog(state==='missing-relics'?'Fjellroglasset trenger alle tre glødesporene.':'Flammefyrsten må svekkes mer før den vil lytte.');return;}b.locked=true;b.fx={kind:'capture',target:'enemy',until:performance.now()+1000};playSound('capture');setBattleLog('Tre glødespor møtes i Fjellroglasset. Ninni står rolig og venter …');renderBattleUI();setTimeout(befriendBoss,1000);return;}b.locked=true;b.fx={kind:'capture',target:'enemy',until:performance.now()+750};playSound('capture');setBattleLog('Roglasset tegner en lysende ring rundt vesenet …');renderBattleUI();setTimeout(()=>{if(Math.random()<captureOdds(b.enemy))captureSuccess();else{setBattleLog(`${C.CREATURES[b.enemy.id].name} brøt ut av lysringen!`);setTimeout(enemyTurn,500);}},750);}
function befriendBoss(){const b=game.battle;if(!b||!b.boss||currentBossFriendship()!=='ready')return;if(!game.caught.includes('flammefyrsten'))game.caught.push('flammefyrsten');const friend=C.makeCreature('flammefyrsten',3);if(game.team.length<3){game.team.push(friend);setBattleLog('Flammefyrsten senker kronen. Den velger å følge Ninni og blir med i flokken!');}else{game.reserve.push(friend);setBattleLog('Flammefyrsten senker kronen. Den velger vennskapet og venter ved leiren!');}game.bossDefeated=true;game.endingType='befriended';game.quest=3;fanfare();updatePanels();setTimeout(()=>finishGame('befriended'),1400);}
function useBerry(){const b=game.battle;if(!b||b.locked||game.inventory.berries<1)return;const unit=game.team[b.active];if(unit.hp>=unit.maxHp)return;b.locked=true;game.inventory.berries--;if(b.trial)game.trial.berriesUsed++;const heal=Math.max(12,Math.round(unit.maxHp*.36));unit.hp=C.clamp(unit.hp+heal,0,unit.maxHp);b.fx={kind:'heal',target:'player',until:performance.now()+520};playSound('heal');setBattleLog(`${C.CREATURES[unit.id].name} spiser et villbær og får ${heal} HP.`);updatePanels();renderBattleUI();setTimeout(enemyTurn,650);}
function materialForArea(area){return area==='forest'?'wood':area==='cave'?'crystal':area==='fjord'?'herb':null;}
function expeditionRewards(unit,battle,xp){unit.bond=(unit.bond||0)+1;const area=battle.roamerArea||areaAt(game.player.x),kind=materialForArea(area);if(kind)game.inventory[kind]=(game.inventory[kind]||0)+1;const trainingId=game.base.assignments.training,trainee=game.reserve.find(u=>u.id===trainingId),trainingLevel=game.base.buildings.training||0;if(trainee&&trainingLevel){const amount=Math.max(6,Math.floor(xp*.2)+trainingLevel*2+(baseWorkerBonus('training')?2:0));C.gainXp(trainee,amount);}const gardenLevel=game.base.buildings.garden||0;if(gardenLevel){game.base.gardenCharge++;const threshold=Math.max(2,5-gardenLevel-(baseWorkerBonus('garden')?1:0));if(game.base.gardenCharge>=threshold){game.base.gardenCharge=0;game.inventory.berries++;toast('Bærhagen har modnet et nytt villbær!');}}panelSignature='';bestiarySignature='';}
function captureSuccess(){const b=game.battle,id=b.enemy.id,c=C.CREATURES[id],isNew=!game.caught.includes(id),active=game.team[b.active];if(isNew)game.caught.push(id);const friend={...b.enemy,hp:Math.max(1,b.enemy.hp),status:{guard:0,weaken:0}};if(game.team.length<3){game.team.push(friend);setBattleLog(`${c.name} ble med i flokken!`);}else if(isNew){game.reserve.push(friend);setBattleLog(`${c.name} ble med og venter trygt ved leiren.`);}else setBattleLog(`${c.name} stoler allerede på dere. Flokken på tre er full.`);expeditionRewards(active,b,18+b.enemy.level*6);fanfare();if(game.caught.length-1>=2&&game.quest<2)game.quest=2;setTimeout(()=>endBattle('capture'),950);}
function switchUnit(){const b=game.battle;if(!b||b.locked)return;const alive=game.team.map((u,i)=>u.hp>0?i:-1).filter(i=>i>=0&&i!==b.active);if(!alive.length)return;b.active=alive[0];b.locked=true;setBattleLog(`${C.CREATURES[game.team[b.active].id].name}, din tur!`);renderBattleUI();setTimeout(enemyTurn,500);}
function finishTrainerBattle(b,unit){const trainer=TRAINERS.find(t=>t.id===b.trainerId);if(!trainer)return endBattle('trainer');const first=(game.trainers[trainer.id]||0)===0;game.trainers[trainer.id]=(game.trainers[trainer.id]||0)+1;if(first)for(const [kind,n] of Object.entries(trainer.reward))game.inventory[kind]+=n;else game.inventory[materialForArea('fjord')]++;if(trainer.guardian)game.trainers.fjordMark=true;setBattleLog(`${trainer.name} nikker. ${first?'Førsteseiersbelønningen er lagt i sekken.':'En ny treningsseier er registrert.'}${trainer.guardian?' Fjordvoktermerket lyser i Reisedagboken!':''}`);updatePanels();setTimeout(()=>endBattle('trainer'),1100);}
function winBattle(){const b=game.battle,unit=game.team[b.active],xp=b.boss?80:22+b.enemy.level*8,before=unit.level;const levels=C.gainXp(unit,xp),learned=before<3&&unit.level>=3?` Nytt angrep: ${C.MOVES[C.CREATURES[unit.id].moves[2]].name}!`:before<5&&unit.level>=5&&C.CREATURES[unit.id].moves[3]?` Ny teknikk kan velges: ${C.MOVES[C.CREATURES[unit.id].moves[3]].name}!`:'';setBattleLog(`${C.CREATURES[b.enemy.id].name} roer seg. ${C.CREATURES[unit.id].name} får ${xp} XP.${levels.length?' Nytt nivå: '+unit.level+'!':''}${learned}`);fanfare();if(b.trial){game.trial.wins++;setTimeout(advanceTrial,900);return;}expeditionRewards(unit,b,xp);if(b.trainerId){setTimeout(()=>finishTrainerBattle(b,unit),700);return;}if(b.boss){game.bossDefeated=true;game.endingType='defeated';game.quest=3;setTimeout(()=>finishGame('defeated'),1100);}else setTimeout(()=>endBattle('win'),950);}
function loseBattle(){const wasTrial=!!game.battle?.trial;setBattleLog(wasTrial?'Sporprøven brytes. Ninni leder den utslitte flokken tilbake til bålet.':'Flokken er utslitt. Ninni løper tilbake til leirbålet!');playSound('lose');setTimeout(()=>{if(wasTrial){game.trial.active=false;game.trial.wins=0;}healTeam();game.player.x=9*TILE;game.player.y=17*TILE;endBattle('lose');toast(wasTrial?'Sporprøven kan forsøkes igjen.':'Bestemor Tora hjalp flokken på beina igjen.');},1200);}
function finishRoamerEncounter(battle=game.battle){if(battle?.roamerArea)game.roamerSpawnAt[battle.roamerArea]=performance.now()+12000;}
function endBattle(reason){const nightTrailBattle=!!game.battle?.nightTrailBattle;finishRoamerEncounter();hide('battleUI');game.battle=null;game.mode='world';game.encounterCooldown=110;updatePanels();saveGame();if(nightTrailBattle&&['win','capture'].includes(reason)){finishNightTrailBattle();return;}if(reason==='capture')toast('Nytt vennskap registrert i reisedagboken!');}
function finishGame(type=game.endingType||'defeated'){game.endingType=type;const time=elapsedSeconds();game.elapsed=time;if(!game.best||time<game.best){game.best=time;localStorage.setItem(BEST_KEY,String(time));}finishRoamerEncounter();hide('battleUI');game.battle=null;game.mode='ending';const befriended=type==='befriended';$('endingTitle').textContent=befriended?'EN NY FJELLVENN':'FJELLET PUSTER IGJEN';$('endingText').textContent=befriended?'Tre glødespor samles i Fjellroglasset. Ninni blir stående uten frykt. Flammefyrsten senker kronen og velger selv å følge flokken som fjellets venn.':'Ninni finner glødesteinen under Flammefyrstens klo. Når steinen legges tilbake i fjellets hjerte, dempes flammene. Fyrsten blir igjen som vokter – rolig, men fortsatt fri.';$('endingStats').innerHTML=`<p><b>Tid:</b> ${formatTime(time)} · <b>Oppdaget:</b> ${game.seen.length}/10 · <b>Venner:</b> ${game.caught.length}/10</p><p>${befriended?'Flammefyrsten venter i flokken eller leirreserven.':'Vennskapsprøven kan forsøkes igjen ved fjellets hjerte.'}</p><p><b>Nytt postgame:</b> Bygg Basecamp og åpne ruten til Fjordbygda.</p><p>Beste tid: ${formatTime(game.best)}</p>`;show('ending');fanfare();updatePanels();saveGame();}
function formatTime(sec){sec=Math.max(0,Math.floor(sec||0));return`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;}

function pause(){if(game.mode==='world'){game.mode='pause';show('pauseScreen');}else if(game.mode==='pause'){hide('pauseScreen');game.mode='world';last=performance.now();}}
function actionKey(code){if(code==='Enter'||code==='KeyE'||code==='Space')interact();if(code==='KeyF')visible('teamPanel')?closePanels():openPanel('teamPanel');if(code==='KeyQ')visible('questPanel')?closePanels():openPanel('questPanel');if(code==='KeyP'||code==='Escape'){if(game.mode==='panel')closePanels();else pause();}}
function bindControls(){
 addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(!e.repeat)actionKey(e.code);});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.mode==='world')pause();});
 const touchPointers=new Map();const releaseDirection=(pointerId)=>{const active=touchPointers.get(pointerId);if(!active)return;touchPointers.delete(pointerId);keys.delete(active.code);active.btn.classList.remove('pressed');try{if(active.btn.hasPointerCapture?.(pointerId))active.btn.releasePointerCapture(pointerId);}catch{}};
 document.querySelectorAll('[data-dir]').forEach(btn=>{const code={up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight'}[btn.dataset.dir];btn.draggable=false;btn.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();releaseDirection(e.pointerId);touchPointers.set(e.pointerId,{code,btn});keys.add(code);btn.classList.add('pressed');try{btn.setPointerCapture?.(e.pointerId);}catch{}},{passive:false});btn.addEventListener('pointermove',e=>{if(!touchPointers.has(e.pointerId))return;const r=btn.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)releaseDirection(e.pointerId);},{passive:false});for(const type of ['pointerup','pointercancel','lostpointercapture','pointerleave'])btn.addEventListener(type,e=>{e.preventDefault();releaseDirection(e.pointerId);},{passive:false});for(const type of ['contextmenu','selectstart','dragstart'])btn.addEventListener(type,e=>e.preventDefault());});
 for(const type of ['pointerup','pointercancel'])document.addEventListener(type,e=>releaseDirection(e.pointerId),{passive:true});$('mobileControls').addEventListener('contextmenu',e=>e.preventDefault());
 $('fullscreenBtn').onclick=toggleFullscreen;document.addEventListener('fullscreenchange',syncFullscreenButton);document.addEventListener('webkitfullscreenchange',syncFullscreenButton);
 $('actionBtn').onclick=interact;$('dialog').onclick=interact;$('mobileTeam').onclick=()=>openPanel('teamPanel');$('mobileQuest').onclick=()=>openPanel('questPanel');$('teamBaseBtn').onclick=()=>{closePanels();openPanel('basePanel');};$('questBaseBtn').onclick=()=>{closePanels();openPanel('basePanel');};$('baseTeamBtn').onclick=()=>{closePanels();openPanel('teamPanel');};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closePanels);
 $('move1Btn').onclick=()=>playerMove(0);$('move2Btn').onclick=()=>playerMove(1);$('move3Btn').onclick=()=>playerMove(2);$('captureBtn').onclick=attemptCapture;$('itemBtn').onclick=useBerry;$('switchBtn').onclick=switchUnit;
 $('newGameBtn').onclick=()=>{if(hasSave()&&!confirm('Starte på nytt og overskrive lagringen?'))return;resetGame();};$('continueBtn').onclick=()=>{if(loadGame()){hide('titleScreen');toast('Velkommen tilbake til Villspor');}};
 $('saveBtn').onclick=()=>saveGame(true);$('resumeBtn').onclick=pause;$('keepPlayingBtn').onclick=()=>{hide('ending');game.mode='world';game.player.x=32*TILE;game.player.y=14*TILE;};$('restartBtn').onclick=resetGame;$('soundBtn').onclick=()=>{game.sound=!game.sound;$('soundBtn').textContent=game.sound?'🔊':'🔇';if(game.sound)playSound('menu');saveGame();};
}

function drawWorld(){const cam=game.camera;ctx.fillStyle='#5e9860';ctx.fillRect(0,0,canvas.width,canvas.height);const x0=Math.max(0,Math.floor(cam.x/TILE)-1),x1=Math.min(WORLD.w,Math.ceil((cam.x+canvas.width)/TILE)+1),y0=Math.max(0,Math.floor(cam.y/TILE)-1),y1=Math.min(WORLD.h,Math.ceil((cam.y+canvas.height)/TILE)+1);
 for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const sx=x*TILE-cam.x,sy=y*TILE-cam.y;let color=x<14?((x+y)%2?'#78ad68':'#72a763'):x<29?((x+y)%2?'#3f754b':'#467d50'):x<42?((x+y)%2?'#4d4e52':'#55565b'):((x+y)%2?'#568b7f':'#609488');if(x>=14&&x<29&&y>=13&&y<=15)color='#a88b5c';if(x>=29&&x<42&&y>=13&&y<=15)color='#5e5651';if(x>=42&&y>=13&&y<=15)color='#b49a68';if(x>=42&&y>21)color='#377f92';ctx.fillStyle=color;ctx.fillRect(sx,sy,TILE+1,TILE+1);if(hash(x,y)%11===0&&x<29){ctx.fillStyle='#bed37a';ctx.fillRect(sx+5,sy+8,3,7);ctx.fillRect(sx+2,sy+10,8,3);}if(x>=29&&x<42&&hash(x,y)%13===0){ctx.fillStyle='#77777d';ctx.fillRect(sx+4,sy+22,24,4);}if(x>=42&&hash(x,y)%13===0){ctx.fillStyle='#d7dfa8';ctx.fillRect(sx+6,sy+9,3,9);}}
 drawRegionDetails();drawAmbience();drawForestCanopy(x0,x1,y0,y1);for(const p of PROPS)drawProp(p);drawBaseStructures();for(const n of RESOURCE_NODES)if(!game.gathered.includes(n.id))drawResourceNode(n);const nightPoint=currentNightTrailPoint();if(nightPoint)drawNightTrail(nightPoint);if(game.bossDefeated)drawTrialStone();for(const r of RELICS)if(!game.relics.includes(r.id))drawRelic(r);for(const s of SECRETS)if(!game.secrets.includes(s.id))drawSecret(s);for(const n of [...NPCS,...TRAINERS])drawNPC(n);drawCampFriends();drawRoamers();drawScentTrail();if(!game.caught.includes('flammefyrsten')&&game.player.x>29*TILE&&game.player.x<42*TILE)drawCreature('flammefyrsten',38*TILE-cam.x,14*TILE-cam.y,1.1,false);
 drawNinni();drawPlayer();drawMiniMap();
}
function drawRegionDetails(){const c=game.camera;
 ctx.fillStyle='#335f76';ctx.fillRect(-c.x,24*TILE-c.y,14*TILE,4*TILE);for(let x=0;x<14;x++){ctx.fillStyle=x%2?'#6cc3cf':'#79d1d2';ctx.fillRect(x*TILE-c.x,25*TILE-c.y+Math.sin(performance.now()/300+x)*3,TILE,3);}
 ctx.fillStyle='#28302f';ctx.fillRect(29*TILE-c.x,0-c.y,2*TILE,WORLD.h*TILE);ctx.fillRect(42*TILE-c.x,0-c.y,2*TILE,WORLD.h*TILE);ctx.fillStyle='#7a6b54';ctx.fillRect(29*TILE-c.x,13*TILE-c.y,2*TILE,3*TILE);ctx.fillRect(42*TILE-c.x,13*TILE-c.y,2*TILE,3*TILE);ctx.fillStyle='#e88745';ctx.fillRect(29*TILE-c.x+13,13*TILE-c.y+12,6,70);ctx.fillStyle='#70c6d0';ctx.fillRect(42*TILE-c.x+13,13*TILE-c.y+12,6,70);
 drawAtmosphere();ctx.fillStyle='#7ac7b4';ctx.font='bold 15px Nunito';ctx.fillText('FURULY CAMPING',2*TILE-c.x,3*TILE-c.y);ctx.fillStyle='#d7d1a7';ctx.fillText('HVISKESKOGEN',18*TILE-c.x,4*TILE-c.y);ctx.fillStyle='#f0a35a';ctx.fillText('GLØDESTEINSHULEN',31*TILE-c.x,5*TILE-c.y);ctx.fillStyle='#d8f1dc';ctx.fillText('FJORDBYGDA',47*TILE-c.x,5*TILE-c.y);
}
function drawAtmosphere(){const c=game.camera,t=performance.now()/1000;ctx.save();ctx.globalAlpha=.28;ctx.fillStyle='#f5e8a5';for(let i=0;i<4;i++){const x=(15+i*4)*TILE-c.x;ctx.beginPath();ctx.moveTo(x,0-c.y);ctx.lineTo(x+70,0-c.y);ctx.lineTo(x+125,19*TILE-c.y);ctx.lineTo(x+75,19*TILE-c.y);ctx.fill();}ctx.globalAlpha=.75;for(let i=0;i<8;i++){const x=(30+i*1.45)*TILE-c.x,y=(7+(i%4)*4.2)*TILE-c.y;ctx.fillStyle=i%2?'#ff7842':'#ffc04c';ctx.beginPath();ctx.arc(x,y,3+Math.sin(t*3+i),0,7);ctx.fill();}ctx.strokeStyle='#302d33';ctx.lineWidth=8;for(let x=30;x<42;x+=2){ctx.beginPath();ctx.moveTo(x*TILE-c.x,0-c.y);ctx.lineTo((x+.45)*TILE-c.x,(2+(x%3))*TILE-c.y);ctx.stroke();}ctx.restore();}
function drawAmbience(){const area=areaAt(game.player.x),group={camp:0,forest:1,cave:2,fjord:0}[area],t=reducedMotion?0:performance.now()/1000,c=game.camera;ctx.save();for(let i=group;i<game.particles.length;i+=3){const p=game.particles[i],baseX=area==='camp'?1:area==='forest'?14:area==='cave'?30:43,width=area==='camp'?12:area==='forest'?15:area==='cave'?12:16,wx=(baseX+.5+(p.x/960)*(width-1))*TILE,wy=(5.5+(p.y/540)*17)*TILE,drift=reducedMotion?0:Math.sin(t*p.speed+p.phase)*9,x=wx-c.x+drift,y=wy-c.y+(reducedMotion?0:Math.cos(t*.55+p.phase)*6);ctx.globalAlpha=.35+.25*(reducedMotion?0:Math.sin(t*.9+p.phase));ctx.fillStyle=area==='camp'?'#ffe67c':area==='forest'?'#c8df83':area==='cave'?'#ff9b62':'#d9f3dd';ctx.beginPath();if(['forest','fjord'].includes(area)){ctx.ellipse(x,y,p.size*1.7,p.size,.45,0,7);}else ctx.arc(x,y,p.size,0,7);ctx.fill();}ctx.restore();}
function drawRoamers(){const c=game.camera,t=reducedMotion?0:performance.now()/400;for(const r of game.roamers){if(r.area!==areaAt(game.player.x))continue;const x=r.x-c.x,y=r.y-c.y,creature=C.CREATURES[r.id];ctx.save();ctx.globalAlpha=.35+.18*Math.sin(t+r.homeX);ctx.fillStyle=C.TYPES[creature.type].color;ctx.beginPath();ctx.arc(x,y+9,17,0,7);ctx.fill();ctx.restore();drawCreature(r.id,x,y,.58,Math.cos(r.angle)<0);}}
function drawCampFriends(){if(areaAt(game.player.x)!=='camp')return;for(const f of campFriends()){const scale=f.id==='flammefyrsten'?.62:.5,unit=allUnits().find(u=>u.id===f.id);drawCreature(f.id,f.x-game.camera.x,f.y-game.camera.y,scale,false,unit?.form);}}
function drawScentTrail(){const now=performance.now();if(now>=game.scent.activeUntil){if(game.scent.activeUntil)hideScent();return;}const target=game.roamers.find(r=>r.token===game.scent.target);if(!target){hideScent();return;}const sx=game.ninni.x-game.camera.x,sy=game.ninni.y-game.camera.y,tx=target.x-game.camera.x,ty=target.y-game.camera.y,t=reducedMotion?0:now/250;ctx.save();ctx.shadowBlur=reducedMotion?0:9;ctx.shadowColor='#ffe77b';ctx.fillStyle='#fff0a0';for(let i=1;i<=5;i++){const k=i/6,x=sx+(tx-sx)*k,y=sy+(ty-sy)*k+(reducedMotion?0:Math.sin(t+i)*5);ctx.globalAlpha=.3+.5*(i/5);ctx.beginPath();ctx.arc(x,y,2.5+i*.35,0,7);ctx.fill();}ctx.restore();}
function drawForestCanopy(x0,x1,y0,y1){const cam=game.camera;for(let y=y0;y<y1;y++)for(let x=Math.max(14,x0);x<Math.min(29,x1);x++){const path=y>=13&&y<=15,clear=x>20&&x<25&&y>7&&y<12;if(path||clear||hash(x,y)%5!==0)continue;const sx=(x+.5)*TILE-cam.x,sy=(y+.6)*TILE-cam.y;ctx.fillStyle='#273f32';ctx.fillRect(sx-5,sy-7,10,25);ctx.fillStyle='#315f3e';ctx.beginPath();ctx.arc(sx,sy-18,20,0,7);ctx.fill();ctx.fillStyle='#54844c';ctx.beginPath();ctx.arc(sx-8,sy-24,11,0,7);ctx.arc(sx+9,sy-21,12,0,7);ctx.fill();}}
function drawNightTrail(p){const t=performance.now()/500,baseX=(p.x+.5)*TILE-game.camera.x,baseY=(p.y+.5)*TILE-game.camera.y;ctx.save();ctx.shadowBlur=10+Math.sin(t)*3;ctx.shadowColor='#ffd96b';ctx.fillStyle='#ffe584';for(let i=0;i<3;i++){const x=baseX+(i-1)*18,y=baseY+(i%2?7:-4);ctx.save();ctx.translate(x,y);ctx.rotate(-.35+i*.18);ctx.beginPath();ctx.ellipse(0,3,5,7,0,0,7);ctx.fill();for(let k=-1;k<=1;k++){ctx.beginPath();ctx.arc(k*5,-5-Math.abs(k),2.4,0,7);ctx.fill();}ctx.restore();}ctx.restore();}
function drawTrialStone(){const t=performance.now()/450,x=(TRIAL.x+.5)*TILE-game.camera.x,y=(TRIAL.y+.5)*TILE-game.camera.y;ctx.save();ctx.shadowBlur=game.trial.completed?7:14;ctx.shadowColor='#e8ce68';ctx.fillStyle='#475c54';ctx.beginPath();ctx.moveTo(x-13,y+13);ctx.lineTo(x-9,y-10);ctx.lineTo(x+7,y-15);ctx.lineTo(x+14,y+13);ctx.fill();ctx.strokeStyle='#ffe681';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-5,y+5);ctx.lineTo(x,y-6);ctx.lineTo(x+5,y+5);ctx.stroke();ctx.globalAlpha=.5+.25*Math.sin(t);ctx.fillStyle='#fff2a0';ctx.fillRect(x-2,y-3,4,4);ctx.restore();}
function drawSecret(s){const t=performance.now()/420,x=(s.x+.5)*TILE-game.camera.x,y=(s.y+.5)*TILE-game.camera.y;ctx.save();ctx.shadowBlur=12+Math.sin(t)*4;ctx.shadowColor='#87dfff';ctx.fillStyle='#75bcd0';for(let i=0;i<3;i++){ctx.save();ctx.translate(x+(i-1)*9,y+Math.abs(i-1)*4);ctx.rotate((i-1)*.25);ctx.fillRect(-3,-9,6,14);ctx.restore();}ctx.fillStyle='#d9fbff';ctx.fillRect(x-2,y-7,4,4);ctx.restore();}
function drawRelic(r){const t=performance.now()/280,x=(r.x+.5)*TILE-game.camera.x,y=(r.y+.5)*TILE-game.camera.y,p=4+Math.sin(t+r.x)*2;ctx.fillStyle='#fff6ae33';ctx.beginPath();ctx.arc(x,y,18+p,0,7);ctx.fill();ctx.fillStyle='#ffe477';ctx.beginPath();ctx.moveTo(x,y-12-p);ctx.lineTo(x+7,y);ctx.lineTo(x,y+12+p);ctx.lineTo(x-7,y);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(x-2,y-2,4,4);}
function drawMiniMap(){const x=canvas.width-192,y=18,w=170,h=38;ctx.fillStyle='#071b1acc';ctx.fillRect(x-5,y-5,w+10,h+10);ctx.fillStyle='#78ad68';ctx.fillRect(x,y,w*14/60,h);ctx.fillStyle='#467d50';ctx.fillRect(x+w*14/60,y,w*15/60,h);ctx.fillStyle='#55565b';ctx.fillRect(x+w*29/60,y,w*13/60,h);ctx.fillStyle='#609488';ctx.fillRect(x+w*42/60,y,w*18/60,h);ctx.fillStyle='#d8c273';ctx.fillRect(x+w*14/60,y+17,w*46/60,5);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x+game.player.x/(WORLD.w*TILE)*w,y+game.player.y/(WORLD.h*TILE)*h,4,0,7);ctx.fill();if(!game.caught.includes('flammefyrsten')){ctx.fillStyle='#ff714a';ctx.fillRect(x+w*38/60,y+17,6,6);}if(!game.trainers.fjordMark){ctx.fillStyle='#70d6df';ctx.fillRect(x+w*57/60,y+17,6,6);}ctx.strokeStyle='#d9c56b';ctx.strokeRect(x-1,y-1,w+2,h+2);}
function drawBaseStructures(){for(const [key,b] of Object.entries(BASE_DEFS)){const level=game.base.buildings[key],x=b.x*TILE-game.camera.x,y=b.y*TILE-game.camera.y;ctx.save();ctx.globalAlpha=level?1:.48;ctx.strokeStyle=level?'#ffe681':'#c8d3af';ctx.lineWidth=2;ctx.setLineDash(level?[]:[5,4]);ctx.strokeRect(x-3,y-3,38,38);ctx.setLineDash([]);ctx.fillStyle=key==='workshop'?'#795545':key==='training'?'#52704b':'#456d61';if(level)ctx.fillRect(x+2,y+12,28,20);ctx.font=`${level?19:15}px sans-serif`;ctx.textAlign='center';ctx.fillText(b.icon,x+16,y+(level?10:23));ctx.font='bold 9px Nunito';ctx.fillStyle='#fff4bf';ctx.fillText(level?`Lv.${level}`:'BYGGEPLASS',x+16,y+31);if(level>1){ctx.fillStyle='#ffd76d';ctx.fillRect(x+5,y+15,5*level,3);}ctx.restore();}ctx.textAlign='left';}
function drawResourceNode(n){const x=(n.x+.5)*TILE-game.camera.x,y=(n.y+.5)*TILE-game.camera.y,t=reducedMotion?0:performance.now()/500;ctx.save();ctx.shadowBlur=reducedMotion?0:8+Math.sin(t+n.x)*3;ctx.shadowColor=n.kind==='wood'?'#e6bd72':n.kind==='crystal'?'#ff9a55':'#b8ed83';ctx.fillStyle=n.kind==='wood'?'#8b603b':n.kind==='crystal'?'#ef8750':'#77b85d';if(n.kind==='wood'){ctx.fillRect(x-12,y-6,24,10);ctx.fillStyle='#d7b172';ctx.fillRect(x-7,y-4,4,6);ctx.fillRect(x+4,y-4,4,6);}else if(n.kind==='crystal'){ctx.beginPath();ctx.moveTo(x,y-15);ctx.lineTo(x+11,y+10);ctx.lineTo(x,y+15);ctx.lineTo(x-10,y+10);ctx.fill();}else{for(let i=-1;i<=1;i++){ctx.beginPath();ctx.ellipse(x+i*7,y-i%2*4,7,12,i*.4,0,7);ctx.fill();}}ctx.restore();}
function drawProp(p){const x=p.x*TILE-game.camera.x,y=p.y*TILE-game.camera.y;if(p.kind==='tent'){ctx.fillStyle='#e8bd58';ctx.beginPath();ctx.moveTo(x,y+28);ctx.lineTo(x+16,y);ctx.lineTo(x+32,y+28);ctx.fill();ctx.fillStyle='#8d4c38';ctx.fillRect(x+14,y+14,4,14);}if(p.kind==='camper'){ctx.fillStyle='#e9e2c4';ctx.fillRect(x-10,y,65,33);ctx.fillStyle='#3a7180';ctx.fillRect(x+29,y+5,20,11);ctx.fillStyle='#cc6650';ctx.fillRect(x-7,y+5,22,6);ctx.fillStyle='#252e2e';ctx.beginPath();ctx.arc(x+2,y+34,8,0,7);ctx.arc(x+45,y+34,8,0,7);ctx.fill();}if(p.kind==='fire'){ctx.fillStyle='#60402f';ctx.fillRect(x+3,y+23,28,6);ctx.fillStyle='#ffca50';ctx.beginPath();ctx.moveTo(x+16,y+2);ctx.lineTo(x+27,y+25);ctx.lineTo(x+6,y+25);ctx.fill();ctx.fillStyle='#ed663c';ctx.fillRect(x+13,y+13,7,12);}if(p.kind==='sign'){ctx.fillStyle='#6b4c32';ctx.fillRect(x+14,y+12,5,24);ctx.fillStyle='#d5b56b';ctx.fillRect(x-4,y,41,18);ctx.fillStyle='#3f543e';ctx.font='bold 10px sans-serif';ctx.fillText('SKOG →',x,y+12);}if(p.kind==='stone'){ctx.fillStyle='#7c7c79';ctx.beginPath();ctx.ellipse(x+16,y+20,15,11,0,0,7);ctx.fill();}if(p.kind==='crystal'){ctx.fillStyle='#ff9a55';ctx.beginPath();ctx.moveTo(x+16,y);ctx.lineTo(x+28,y+18);ctx.lineTo(x+16,y+33);ctx.lineTo(x+5,y+18);ctx.fill();}}
function drawNPC(n){const x=n.x-game.camera.x,y=n.y-game.camera.y;ctx.fillStyle=n.color;ctx.fillRect(x-10,y-10,20,23);ctx.fillStyle='#f3cc9d';ctx.fillRect(x-7,y-20,14,13);ctx.fillStyle='#172627';ctx.fillRect(x-4,y-17,2,2);ctx.fillRect(x+3,y-17,2,2);ctx.fillStyle='#fff';ctx.font='12px sans-serif';ctx.textAlign='center';ctx.fillText(n.icon,x,y-24);ctx.textAlign='left';}
function drawPlayer(){const x=game.player.x-game.camera.x,y=game.player.y-game.camera.y,step=Math.sin(game.moved*.12)*2;ctx.fillStyle='#102b2a55';ctx.beginPath();ctx.ellipse(x,y+14,14,5,0,0,7);ctx.fill();ctx.fillStyle='#172f3f';ctx.fillRect(x-8,y+5+step,6,10);ctx.fillRect(x+2,y+5-step,6,10);ctx.fillStyle='#264d69';ctx.fillRect(x-10,y-10,20,21);ctx.fillStyle='#d7ad7e';ctx.fillRect(x-8,y-21,16,13);ctx.fillStyle='#d45f42';ctx.fillRect(x-10,y-25,20,7);ctx.fillStyle='#873f32';ctx.fillRect(x-13,y-8,5,15);ctx.fillStyle='#f0d35b';const handX=game.player.dir==='right'?8:-12;ctx.fillRect(x+handX,y-5,4,9);ctx.fillStyle='#1b2d31';ctx.fillRect(x-5,y-17,3,3);ctx.fillRect(x+3,y-17,3,3);}
function drawNinni(){const x=game.ninni.x-game.camera.x,y=game.ninni.y-game.camera.y;ctx.fillStyle='#102b2a44';ctx.beginPath();ctx.ellipse(x,y+9,16,5,0,0,7);ctx.fill();ctx.fillStyle='#f8f3df';for(const [dx,dy,r] of [[-7,-1,9],[1,-3,10],[8,-1,8],[9,-10,8]]){ctx.beginPath();ctx.arc(x+dx,y+dy,r,0,7);ctx.fill();}ctx.fillStyle='#d7cbb2';ctx.beginPath();ctx.ellipse(x+12,y-13,4,8,-.45,0,7);ctx.fill();ctx.fillStyle='#d74d48';ctx.fillRect(x+4,y-5,10,3);ctx.fillStyle='#1d2a29';ctx.fillRect(x+10,y-12,3,3);ctx.fillRect(x+15,y-8,4,3);ctx.strokeStyle='#f8f3df';ctx.lineWidth=5;ctx.beginPath();ctx.arc(x-13,y-8,9,.3,4.9);ctx.stroke();ctx.fillStyle='#eee5ce';ctx.fillRect(x-7,y+5,4,7);ctx.fillRect(x+5,y+5,4,7);}
function drawNatureAura(x,y,scale,form){if(!form)return;ctx.save();ctx.strokeStyle=form==='spor'?'#ffd86f':'#bde9d1';ctx.lineWidth=2.5*scale;ctx.globalAlpha=.8;ctx.setLineDash(form==='spor'?[6*scale,4*scale]:[]);ctx.beginPath();ctx.ellipse(x,y+18*scale,32*scale,11*scale,0,0,7);ctx.stroke();ctx.restore();}
function drawCreature(id,x,y,scale=1,flip=false,form=null){const c=C.CREATURES[id],s=scale,art=creatureArt[id];drawNatureAura(x,y,s,form);if(art?.complete&&art.naturalWidth){ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);const size=96*s;ctx.drawImage(art,-size/2,-size*.62,size,size);ctx.restore();return;}ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(0,22*s,25*s,7*s,0,0,7);ctx.fill();const [a,b,d]=c.colors;ctx.fillStyle=a;
 if(c.shape==='fox'){ctx.beginPath();ctx.ellipse(0,0,24*s,18*s,0,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(-18*s,-12*s);ctx.lineTo(-12*s,-32*s);ctx.lineTo(-2*s,-15*s);ctx.moveTo(18*s,-12*s);ctx.lineTo(12*s,-32*s);ctx.lineTo(2*s,-15*s);ctx.fill();ctx.fillStyle=b;ctx.beginPath();ctx.moveTo(-7*s,1*s);ctx.lineTo(7*s,1*s);ctx.lineTo(0,13*s);ctx.fill();}
 else if(c.shape==='moss'){ctx.beginPath();ctx.arc(0,0,26*s,0,7);ctx.fill();ctx.fillStyle=b;for(let i=-2;i<=2;i++){ctx.beginPath();ctx.arc(i*10*s,-20*s,10*s,0,7);ctx.fill();}}
 else if(c.shape==='otter'){ctx.beginPath();ctx.ellipse(0,1*s,17*s,27*s,0,0,7);ctx.fill();ctx.fillStyle=b;ctx.beginPath();ctx.ellipse(0,7*s,10*s,14*s,0,0,7);ctx.fill();}
 else if(c.shape==='crab'){ctx.beginPath();ctx.ellipse(0,2*s,25*s,18*s,0,0,7);ctx.fill();ctx.strokeStyle=b;ctx.lineWidth=7*s;for(const side of [-1,1]){ctx.beginPath();ctx.moveTo(side*17*s,0);ctx.lineTo(side*32*s,-12*s);ctx.stroke();}}
 else if(c.shape==='bird'){ctx.beginPath();ctx.ellipse(0,0,17*s,24*s,0,0,7);ctx.fill();ctx.fillStyle=b;ctx.beginPath();ctx.ellipse(-16*s,2*s,15*s,8*s,-.5,0,7);ctx.ellipse(16*s,2*s,15*s,8*s,.5,0,7);ctx.fill();}
 else if(c.shape==='bat'){ctx.beginPath();ctx.arc(0,0,16*s,0,7);ctx.fill();ctx.fillStyle=b;for(const side of [-1,1]){ctx.beginPath();ctx.moveTo(side*10*s,-8*s);ctx.lineTo(side*35*s,-24*s);ctx.lineTo(side*29*s,8*s);ctx.lineTo(side*12*s,5*s);ctx.fill();}}
 else{ctx.beginPath();ctx.ellipse(0,0,29*s,35*s,0,0,7);ctx.fill();ctx.fillStyle=b;for(const side of [-1,1]){ctx.beginPath();ctx.moveTo(side*12*s,-15*s);ctx.lineTo(side*42*s,-35*s);ctx.lineTo(side*31*s,10*s);ctx.fill();}ctx.fillStyle=d;ctx.beginPath();ctx.moveTo(-12*s,-27*s);ctx.lineTo(-4*s,-48*s);ctx.lineTo(2*s,-29*s);ctx.lineTo(12*s,-49*s);ctx.lineTo(14*s,-23*s);ctx.fill();}
 ctx.fillStyle='#fff';ctx.fillRect(-9*s,-6*s,6*s,7*s);ctx.fillRect(5*s,-6*s,6*s,7*s);ctx.fillStyle=d;ctx.fillRect(-7*s,-4*s,3*s,4*s);ctx.fillRect(7*s,-4*s,3*s,4*s);ctx.restore();}
function drawBattle(){const b=game.battle;if(!b)return;const now=performance.now(),t=now/1000,fx=b.fx&&now<b.fx.until?b.fx:null,shake=fx&&['hit','burst'].includes(fx.kind)?Math.sin(now*.11)*6:0;ctx.save();ctx.translate(shake,0);const sky=ctx.createLinearGradient(0,0,0,canvas.height);if(b.boss){sky.addColorStop(0,'#241827');sky.addColorStop(.62,'#60312f');sky.addColorStop(1,'#bd5336');}else{sky.addColorStop(0,'#9ac8bd');sky.addColorStop(.58,'#c7dba9');sky.addColorStop(1,'#5f9361');}ctx.fillStyle=sky;ctx.fillRect(-10,0,canvas.width+20,canvas.height);ctx.fillStyle=b.boss?'#4a292e':'#477655';for(let i=0;i<12;i++){const x=i*95-20,h=70+(i%3)*25;ctx.beginPath();ctx.moveTo(x,350);ctx.lineTo(x+38,350-h);ctx.lineTo(x+76,350);ctx.fill();}ctx.fillStyle=b.boss?'#783a31':'#6c9d67';for(let i=0;i<14;i++){ctx.beginPath();ctx.arc(i*80+(i%2)*20,390+Math.sin(t+i)*5,55,0,7);ctx.fill();}ctx.fillStyle=b.boss?'#f08045':'#e6d99a';const compact=innerHeight<=650&&innerWidth>innerHeight,enemyY=compact?215:260,playerY=compact?320:380;if(b.boss&&game.relics.length===3){ctx.save();ctx.shadowBlur=currentBossFriendship()==='ready'?24:14;ctx.shadowColor='#ffe873';for(let i=0;i<3;i++){const a=t*1.4+i*Math.PI*2/3,x=710+Math.cos(a)*105,y=enemyY-25+Math.sin(a)*42;ctx.fillStyle=i===0?'#fff3a0':i===1?'#ffb958':'#ffe873';ctx.beginPath();ctx.arc(x,y,currentBossFriendship()==='ready'?8:5,0,7);ctx.fill();}ctx.restore();}ctx.beginPath();ctx.ellipse(710,enemyY+30,145,45,0,0,7);ctx.ellipse(245,playerY+30,165,48,0,0,7);ctx.fill();const enemyKick=fx&&fx.target==='enemy'&&['hit','burst'].includes(fx.kind)?Math.sin(now*.15)*14:0,playerKick=fx&&fx.target==='player'&&['hit','burst'].includes(fx.kind)?Math.sin(now*.15)*14:0;drawCreature(b.enemy.id,710+enemyKick,enemyY,b.boss?2.2:1.8,false);drawCreature(game.team[b.active].id,245+playerKick,playerY,2,true,game.team[b.active].form);if(fx){const x=fx.target==='enemy'?710:245,y=fx.target==='enemy'?enemyY-15:playerY-25,color=fx.kind==='heal'?'#8dff9a':fx.kind==='capture'?'#ffe873':'#fff2b0';ctx.strokeStyle=color;ctx.lineWidth=fx.kind==='burst'?8:5;for(let i=0;i<(fx.kind==='burst'?8:4);i++){const a=i*Math.PI/4+t*2,r=28+(fx.until-now)*.08;ctx.beginPath();ctx.moveTo(x+Math.cos(a)*12,y+Math.sin(a)*12);ctx.lineTo(x+Math.cos(a)*r,y+Math.sin(a)*r);ctx.stroke();}if(fx.kind==='capture'){ctx.beginPath();ctx.arc(x,y,45+Math.sin(t*9)*8,0,7);ctx.stroke();}}ctx.fillStyle='#19312f';ctx.font='900 22px Nunito';ctx.fillText(b.boss?'FJELLETS HJERTE':'VILLSPOR',28,42);ctx.restore();}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);if(game.mode==='battle')drawBattle();else drawWorld();}
function update(dt){if(game.mode==='world'){const now=performance.now();updateRoamers(dt,now);let dx=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0),dy=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0);if(dx&&dy){dx*=.707;dy*=.707;}tryMove(dx,dy,dt);game.camera.x=C.clamp(game.player.x-canvas.width/2,0,WORLD.w*TILE-canvas.width);game.camera.y=C.clamp(game.player.y-canvas.height/2,0,WORLD.h*TILE-canvas.height);if(now-game.lastSave>30000)saveGame();if(now-lastPanelUpdate>250){updatePanels();lastPanelUpdate=now;}}}
function loop(ts){const dt=Math.min(.04,(ts-last)/1000||0);last=ts;syncModeUI();update(dt);draw();raf=requestAnimationFrame(loop);}

function init(){bindControls();$('continueBtn').classList.toggle('hidden',!hasSave());$('titleScreen').classList.add('visible');updatePanels();raf=requestAnimationFrame(loop);}
window.VillsporDebug={get game(){return game;},core:C,runtimeConfig,playSound,startBattle,startTrainerBattle,spawnRoamers,updateRoamers,forceRoamer,engageRoamer,activateScent,upgradeBuilding,assignBuilding,collectResource,chooseUnitForm,chooseUnitMove,isRoamerSafe(x,y){return safeRoamerPosition(x*TILE,y*TILE);},setPosition(x,y){game.player.x=x*TILE;game.player.y=y*TILE;},interact,playerMove,attemptCapture,useBerry,switchUnit,refreshBattle:renderBattleUI,refreshPanels(){panelSignature='';bestiarySignature='';updatePanels();},saveGame,loadGame,resetGame,getSnapshot(){return{mode:game.mode,quest:game.quest,team:game.team.map(u=>({id:u.id,level:u.level,hp:u.hp,maxHp:u.maxHp,bond:u.bond,form:u.form,selectedMoves:u.selectedMoves})),reserve:game.reserve.map(u=>({id:u.id,level:u.level,hp:u.hp,maxHp:u.maxHp,bond:u.bond,form:u.form,selectedMoves:u.selectedMoves})),seen:[...game.seen],caught:[...game.caught],relics:[...game.relics],secrets:[...game.secrets],sideQuests:{...game.sideQuests},nightTrail:{...game.nightTrail},trial:{...game.trial},inventory:{...game.inventory},base:JSON.parse(JSON.stringify(game.base)),gathered:[...game.gathered],trainers:{...game.trainers},roamers:game.roamers.map(r=>({token:r.token,id:r.id,area:r.area,x:r.x,y:r.y})),scent:{...game.scent},particles:game.particles.length,reducedMotion,campFriends:campFriends().map(f=>f.id),bossDefeated:game.bossDefeated,endingType:game.endingType,bossFriendship:currentBossFriendship(),area:areaAt(game.player.x)};},forceWorld(){hide('titleScreen');game.started=true;game.mode='world';game.startTime=game.startTime||Date.now();if(!game.team.length)game.team=[C.makeCreature('mosemurr',1)];spawnRoamers();},finishGame};
init();
})();
