(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.VillsporCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const TYPES={ILD:{strong:'VEKST',weak:'VANN',color:'#f06a45',icon:'🔥'},VEKST:{strong:'VANN',weak:'ILD',color:'#70b85f',icon:'🌿'},VANN:{strong:'ILD',weak:'VEKST',color:'#4bb8d3',icon:'💧'}};
const MOVES={
  glosprang:{name:'Glødesprang',type:'ILD',power:14},askesnurr:{name:'Askespinn',type:'ILD',power:10,effect:'weaken'},
  rotgrep:{name:'Rotgrep',type:'VEKST',power:13},sporevind:{name:'Sporevind',type:'VEKST',power:9,effect:'heal'},
  skumsprut:{name:'Skumsprut',type:'VANN',power:14},duggslor:{name:'Duggslør',type:'VANN',power:8,effect:'guard'},
  konglekast:{name:'Konglekast',type:'VEKST',power:15},barkbrak:{name:'Barkbrak',type:'VEKST',power:11},
  bobleblink:{name:'Bobleblink',type:'VANN',power:12},fossedunk:{name:'Fossedunk',type:'VANN',power:16},
  kullnebb:{name:'Kullnebb',type:'ILD',power:13},vingegnist:{name:'Vingegnist',type:'ILD',power:15},
  flammesverd:{name:'Flammesverd',type:'ILD',power:18},lavastorm:{name:'Lavastorm',type:'ILD',power:21},
  ildspor:{name:'Ildspor',type:'ILD',power:12},mosevern:{name:'Mosevern',type:'VEKST',power:7,effect:'guard'},
  kildepust:{name:'Kildepust',type:'VANN',power:7,effect:'heal'},harpikssnor:{name:'Harpikssnor',type:'VEKST',power:8,effect:'weaken'},
  taakeskjold:{name:'Tåkeskjold',type:'VANN',power:7,effect:'guard'},sotdis:{name:'Sotdis',type:'ILD',power:8,effect:'weaken'},
  glodhjerte:{name:'Glødhjerte',type:'ILD',power:9,effect:'heal'},
  revblink:{name:'Revblink',type:'ILD',power:18},rotborg:{name:'Rotborg',type:'VEKST',power:9,effect:'guard'},
  stromstot:{name:'Strømstøt',type:'VANN',power:18},konglevern:{name:'Konglevern',type:'VEKST',power:9,effect:'guard'},
  taakestup:{name:'Tåkestup',type:'VANN',power:13,effect:'weaken'},nattglor:{name:'Nattglør',type:'ILD',power:18},
  lyngsteg:{name:'Lyngsteg',type:'VEKST',power:12,effect:'guard'},sevjesang:{name:'Sevjesang',type:'VEKST',power:9,effect:'heal'},
  solstup:{name:'Solstup',type:'ILD',power:19},stormkall:{name:'Stormkall',type:'VANN',power:16,effect:'weaken'},
  tidevern:{name:'Tidevern',type:'VANN',power:9,effect:'heal'}
};
const CREATURES={
  gnistrev:{id:'gnistrev',name:'Gnistrev',type:'ILD',role:'Rask sporjeger',bio:'En sky revegnist som lager små bål når den nyser.',trait:{name:'Første gnist',description:'+10 % skade over 80 % HP'},base:{hp:42,attack:14,defense:9,speed:14},moves:['glosprang','askesnurr','ildspor','revblink'],colors:['#f27b45','#ffd568','#6b3430'],shape:'fox'},
  mosemurr:{id:'mosemurr',name:'Mosemurr',type:'VEKST',role:'Seig beskytter',bio:'En lun skogsånd som sover under mosekledde steiner.',trait:{name:'Moselag',description:'8 % mindre skade over halv HP'},base:{hp:48,attack:11,defense:14,speed:8},moves:['rotgrep','sporevind','mosevern','rotborg'],colors:['#6da85c','#b7d875','#355e45'],shape:'moss'},
  bekkskvett:{id:'bekkskvett',name:'Bekkskvett',type:'VANN',role:'Stødig helbreder',bio:'En rastløs bekkunge som alltid svømmer motstrøms.',trait:{name:'Kildepuls',description:'Helbredelse gir 18 % HP'},base:{hp:44,attack:13,defense:10,speed:13},moves:['skumsprut','duggslor','kildepust','stromstot'],colors:['#55bdd3','#d7f4e9','#28617d'],shape:'otter'},
  kongleklo:{id:'kongleklo',name:'Kongleklo',type:'VEKST',role:'Herdet taktiker',bio:'Samler blanke ting i kongleskallet sitt.',trait:{name:'Hardt skall',description:'10 % mindre skade under halv HP'},base:{hp:50,attack:14,defense:13,speed:7},moves:['konglekast','barkbrak','harpikssnor','konglevern'],colors:['#8c6741','#79ad52','#403b2d'],shape:'crab'},
  fjordfnugg:{id:'fjordfnugg',name:'Fjordfnugg',type:'VANN',role:'Rask tåkevokter',bio:'Et fjærlett fjordvesen som varsler regn.',trait:{name:'Medvind',description:'+8 % skade når den er raskest'},base:{hp:40,attack:12,defense:9,speed:17},moves:['bobleblink','fossedunk','taakeskjold','taakestup'],colors:['#91dbe4','#f0fff3','#527c9c'],shape:'bird'},
  kullvinge:{id:'kullvinge',name:'Kullvinge',type:'ILD',role:'Snikende svekker',bio:'Trives i varme bergsprekker og tegner med sot.',trait:{name:'Sotmerke',description:'Svekkelse varer én ekstra runde'},base:{hp:43,attack:15,defense:8,speed:15},moves:['kullnebb','vingegnist','sotdis','nattglor'],colors:['#332f3e','#f16a42','#ffc85a'],shape:'bat'},
  lynglo:{id:'lynglo',name:'Lynglo',type:'VEKST',role:'Smidig lyngvokter',bio:'En langbeint lyngkatt som skjuler spor under lilla blomster.',trait:{name:'Lyngstille',description:'Skjold varer én ekstra runde'},base:{hp:46,attack:13,defense:12,speed:14},moves:['rotgrep','harpikssnor','lyngsteg','sevjesang'],colors:['#8565a8','#bfdf7a','#3f5d45'],shape:'lynx'},
  ravnbluss:{id:'ravnbluss',name:'Ravnbluss',type:'ILD',role:'Lynrask glødespeider',bio:'En svart fjordravn med solglør langs vingefjærene.',trait:{name:'Solvinge',description:'+8 % skade når den er raskest'},base:{hp:41,attack:15,defense:9,speed:18},moves:['kullnebb','askesnurr','vingegnist','solstup'],colors:['#292d3b','#ef7846','#ffd468'],shape:'raven'},
  stormhjort:{id:'stormhjort',name:'Stormhjort',type:'VANN',role:'Stødig fjordvokter',bio:'Bærer regnskyer mellom geviret og roer sjøen med tunge steg.',trait:{name:'Flovern',description:'8 % mindre skade under halv HP'},base:{hp:58,attack:14,defense:15,speed:9},moves:['skumsprut','duggslor','stormkall','tidevern'],colors:['#527d9e','#bce4df','#2f465d'],shape:'deer'},
  flammefyrsten:{id:'flammefyrsten',name:'Flammefyrsten',type:'ILD',role:'Kraftig fjellvokter',bio:'Fjellets stolte, eldgamle vokter. Et vennskap som må fortjenes.',trait:{name:'Glødekrone',description:'10 % mindre skade fra typefordel'},base:{hp:64,attack:16,defense:14,speed:11},moves:['flammesverd','lavastorm','glodhjerte'],colors:['#9d2e28','#ff6b32','#ffd45a'],shape:'dragon',boss:true,legendary:true}
};
function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
const FORM_PATHS={spor:{name:'Sporform',description:'+12 % angrep og fart'},vern:{name:'Vernform',description:'+12 % HP og forsvar'}};
function statsFor(id,level=1,form=null){const c=CREATURES[id];if(!c)throw new Error('Ukjent vesen: '+id);const s={maxHp:c.base.hp+(level-1)*6,attack:c.base.attack+(level-1)*2,defense:c.base.defense+(level-1)*2,speed:c.base.speed+(level-1)};if(form==='spor'){s.attack=Math.round(s.attack*1.12);s.speed=Math.round(s.speed*1.12);}if(form==='vern'){s.maxHp=Math.round(s.maxHp*1.12);s.defense=Math.round(s.defense*1.12);}return s;}
function makeCreature(id,level=1){const s=statsFor(id,level);return{id,level,xp:0,hp:s.maxHp,maxHp:s.maxHp,bond:0,form:null,selectedMoves:null,status:{guard:0,weaken:0}};}
function typeMultiplier(moveType,targetType){if(TYPES[moveType].strong===targetType)return 1.5;if(TYPES[moveType].weak===targetType)return .67;return 1;}
function xpNeeded(level){return 24+level*16;}
function gainXp(unit,amount){const levels=[];unit.xp+=amount;while(unit.xp>=xpNeeded(unit.level)){unit.xp-=xpNeeded(unit.level);unit.level++;const s=statsFor(unit.id,unit.level,unit.form);const gain=s.maxHp-unit.maxHp;unit.maxHp=s.maxHp;unit.hp=Math.min(unit.maxHp,unit.hp+gain+6);levels.push(unit.level);}return levels;}
function traitDamageFactor(attacker,defender,mult){let factor=1;const as=statsFor(attacker.id,attacker.level,attacker.form),ds=statsFor(defender.id,defender.level,defender.form);if(attacker.id==='gnistrev'&&attacker.hp/attacker.maxHp>.8)factor*=1.1;if(['fjordfnugg','ravnbluss'].includes(attacker.id)&&as.speed>ds.speed)factor*=1.08;if(defender.id==='mosemurr'&&defender.hp/defender.maxHp>.5)factor*=.92;if(['kongleklo','stormhjort'].includes(defender.id)&&defender.hp/defender.maxHp<.5)factor*=defender.id==='kongleklo'?.9:.92;if(defender.id==='flammefyrsten'&&mult>1)factor*=.9;return factor;}
function calcDamage(attacker,defender,moveId,roll=.85){const move=MOVES[moveId];const a=statsFor(attacker.id,attacker.level,attacker.form);const d=statsFor(defender.id,defender.level,defender.form);const weaken=attacker.status?.weaken?0.78:1;const guard=defender.status?.guard?0.72:1;const mult=typeMultiplier(move.type,CREATURES[defender.id].type);const raw=(move.power+a.attack*.72-d.defense*.36)*clamp(roll,.75,1)*mult*weaken*guard*traitDamageFactor(attacker,defender,mult);return{damage:Math.max(2,Math.round(raw)),mult,move};}
function applyMove(attacker,defender,moveId,roll=.85){const result=calcDamage(attacker,defender,moveId,roll);defender.hp=clamp(defender.hp-result.damage,0,defender.maxHp);const effect=result.move.effect;if(effect==='heal')attacker.hp=clamp(attacker.hp+Math.round(attacker.maxHp*(attacker.id==='bekkskvett'?.18:.14)),0,attacker.maxHp);if(effect==='guard')attacker.status.guard=attacker.id==='lynglo'?3:2;if(effect==='weaken')defender.status.weaken=attacker.id==='kullvinge'?3:2;return result;}
function tickStatus(unit){for(const k of ['guard','weaken'])if(unit.status?.[k]>0)unit.status[k]--;}
function availableMoveIds(unit){const moves=CREATURES[unit.id].moves;return moves.slice(0,unit.level>=5?4:unit.level>=3?3:2);}
function unlockedMoveIds(unit){const available=availableMoveIds(unit);if(Array.isArray(unit.selectedMoves)){const selected=unit.selectedMoves.filter((id,i,a)=>available.includes(id)&&a.indexOf(id)===i).slice(0,3);if(selected.length>=Math.min(3,available.length))return selected;}return available.slice(0,3);}
function setThirdMove(unit,moveId){const available=availableMoveIds(unit),moves=CREATURES[unit.id].moves;if(!available.includes(moveId)||!moves.slice(2).includes(moveId))return false;unit.selectedMoves=[moves[0],moves[1],moveId];return true;}
function canChooseForm(unit){return!!unit&&!CREATURES[unit.id]?.boss&&unit.level>=5&&(unit.bond||0)>=3&&!unit.form;}
function chooseNatureForm(unit,form){if(!canChooseForm(unit)||!FORM_PATHS[form])return false;const oldMax=unit.maxHp||statsFor(unit.id,unit.level).maxHp,ratio=Math.max(0,unit.hp)/oldMax;unit.form=form;const s=statsFor(unit.id,unit.level,form);unit.maxHp=s.maxHp;unit.hp=Math.round(s.maxHp*ratio);return true;}
function chooseEnemyMove(attacker,defender,roll=.5){const options=unlockedMoveIds(attacker).map(id=>{const move=MOVES[id],result=calcDamage(attacker,defender,id,.9);let score=result.damage+(result.mult>1?10:result.mult<1?-5:0);if(move.effect==='heal')score+=attacker.hp/attacker.maxHp<.45?22:-12;if(move.effect==='guard')score+=attacker.status?.guard?-9:7;if(move.effect==='weaken')score+=defender.status?.weaken?-8:9;return{id,score};}).sort((a,b)=>b.score-a.score);if(options.length>1&&roll>.82)return options[1].id;return options[0].id;}
function captureChance(unit){if(CREATURES[unit.id].boss)return 0;return clamp(.22+(1-unit.hp/unit.maxHp)*.68,0.22,.9);}
function canCapture(unit,roll){return roll<captureChance(unit);}
function bossFriendshipState(unit,relicCount=0,alreadyCaught=false){if(!unit||unit.id!=='flammefyrsten')return'not-boss';if(alreadyCaught)return'already';if(relicCount<3)return'missing-relics';if(unit.hp/unit.maxHp>.25)return'weaken';return'ready';}
function validateData(){const errors=[];const ids=Object.keys(CREATURES);if(ids.filter(id=>!CREATURES[id].boss).length!==9)errors.push('Må ha ni fangbare vesener');for(const [id,c] of Object.entries(CREATURES)){if(!TYPES[c.type])errors.push(id+' har ugyldig type');if(!c.trait?.name||!c.trait?.description)errors.push(id+' mangler egenskap');if(c.moves.length<(c.boss?3:4))errors.push(id+' mangler teknikker');for(const m of c.moves)if(!MOVES[m])errors.push(id+' viser til ukjent angrep '+m);}return errors;}
return{TYPES,MOVES,CREATURES,FORM_PATHS,clamp,statsFor,makeCreature,typeMultiplier,xpNeeded,gainXp,calcDamage,applyMove,tickStatus,availableMoveIds,unlockedMoveIds,setThirdMove,canChooseForm,chooseNatureForm,chooseEnemyMove,captureChance,canCapture,bossFriendshipState,validateData};
});
