(()=>{
'use strict';
const C=window.VillsporCore;
const $=id=>document.getElementById(id);
const canvas=$('game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const TILE=32,WORLD={w:42,h:28};
const SAVE_KEY='villspor-save-v1',BEST_KEY='villspor-best-v1';
const encounters={forest:['gnistrev','mosemurr','bekkskvett','kongleklo','fjordfnugg'],cave:['kullvinge','gnistrev','bekkskvett']};
const keys=new Set();
let raf=0,last=0,toastTimer=0,audioCtx=null,lastPanelUpdate=0,uiMode='';

const fresh=()=>({
 mode:'title',started:false,paused:false,player:{x:6*TILE,y:14*TILE,dir:'down',speed:142},trail:[],ninni:{x:5.5*TILE,y:14.5*TILE},camera:{x:0,y:0},
 team:[],reserve:[],seen:[],caught:[],quest:0,bossDefeated:false,endingType:null,dialogs:{tora:false,loke:false,siv:false},sideQuests:{loke:'available',siv:'available'},secrets:[],trial:{completed:false,active:false,wins:0,runs:0},relics:[],inventory:{berries:2},
 moved:0,encounterCooldown:150,startTime:0,elapsed:0,best:Number(localStorage.getItem(BEST_KEY)||0),battle:null,message:'',sound:true,lastSave:0
});
let game=fresh();
const creatureArt={};for(const id of Object.keys(C.CREATURES)){const img=new Image();img.decoding='async';img.src=`assets/creatures/${id}.svg`;creatureArt[id]=img;}
let panelSignature='',bestiarySignature='';

const NPCS=[
 {id:'tora',name:'Bestemor Tora',x:7*TILE,y:11*TILE,icon:'👵',color:'#a45248'},
 {id:'loke',name:'Loke',x:12*TILE,y:18*TILE,icon:'🧒',color:'#4c78a8'},
 {id:'siv',name:'Skogvokter Siv',x:23*TILE,y:9*TILE,icon:'🧭',color:'#5f8152'}
];
const PROPS=[
 {kind:'tent',x:3,y:6},{kind:'tent',x:10,y:7},{kind:'camper',x:4,y:19},{kind:'fire',x:9,y:18},
 {kind:'sign',x:13,y:14},{kind:'stone',x:31,y:8},{kind:'stone',x:35,y:19},{kind:'crystal',x:37,y:10}
];
const RELICS=[{id:'skoglys',x:18,y:8},{id:'bekkelys',x:25,y:20},{id:'hulelys',x:33,y:18}];
const SECRETS=[{id:'stjernestein',x:34,y:9}];
const TRIAL={x:11,y:20,enemies:['kongleklo','kullvinge','fjordfnugg']};

function saveGame(show=false){if(!game.started)return;game.elapsed=elapsedSeconds();const data={player:game.player,team:game.team,reserve:game.reserve,seen:game.seen,caught:game.caught,quest:game.quest,bossDefeated:game.bossDefeated,endingType:game.endingType,dialogs:game.dialogs,sideQuests:game.sideQuests,secrets:game.secrets,trial:{...game.trial,active:false,wins:0},relics:game.relics,inventory:game.inventory,elapsed:game.elapsed,best:game.best,sound:game.sound};localStorage.setItem(SAVE_KEY,JSON.stringify(data));game.lastSave=performance.now();if(show)toast('Eventyret er lagret ✓');}
function hasSave(){try{return!!JSON.parse(localStorage.getItem(SAVE_KEY)||'null');}catch{return false;}}
function loadGame(){try{const d=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(!d)return false;game=fresh();Object.assign(game,d,{started:true,mode:'world',battle:null,startTime:Date.now()-(d.elapsed||0)*1000});game.player={...fresh().player,...d.player};game.team=(d.team||[]).map(u=>({...u,status:u.status||{guard:0,weaken:0}}));game.reserve=(d.reserve||[]).map(u=>({...u,status:u.status||{guard:0,weaken:0}}));game.relics=d.relics||[];game.secrets=d.secrets||[];game.sideQuests={...fresh().sideQuests,...d.sideQuests};game.trial={...fresh().trial,...d.trial,active:false,wins:0};game.inventory={...fresh().inventory,...d.inventory};if(game.caught.includes('flammefyrsten')){game.bossDefeated=true;game.endingType='befriended';}else if(game.bossDefeated&&!game.endingType)game.endingType='defeated';game.trail=[];game.ninni={x:game.player.x-20,y:game.player.y+12};panelSignature='';bestiarySignature='';updatePanels();return true;}catch(e){console.warn('Kunne ikke laste lagring',e);return false;}}
function resetGame(){localStorage.removeItem(SAVE_KEY);game=fresh();startNew();}
function startNew(){game=fresh();game.started=true;game.mode='world';game.startTime=Date.now();game.team=[C.makeCreature('mosemurr',1)];game.seen=['mosemurr'];game.caught=['mosemurr'];hide('titleScreen');showDialog('Bestemor Tora','Ninni fant dette lille Mosemurr-vesenet under bobilen i natt. Noe har skremt naturåndene ut av skogen …','👵',()=>showDialog('Bestemor Tora','Gå østover. Bli venn med minst to forskjellige vesener, så kan dere åpne fjellporten. Roglasset fanger bare et svekket vesen.','👵',()=>{game.quest=1;game.dialogs.tora=true;updatePanels();saveGame();toast('Nytt mål: Fang minst to ulike villvesener');}));updatePanels();tone(330,.08);}
function elapsedSeconds(){return game.startTime?Math.floor((Date.now()-game.startTime)/1000):game.elapsed||0;}

function show(id){const el=$(id);el.classList.remove('hidden');if(el.classList.contains('panel-screen'))el.classList.add('visible');}
function hide(id){$(id).classList.add('hidden');$(id).classList.remove('visible');}
function visible(id){return!$(id).classList.contains('hidden')||$(id).classList.contains('visible');}
function syncModeUI(){if(uiMode===game.mode)return;uiMode=game.mode;document.body.dataset.gameMode=game.mode;}
function fullscreenElement(){return document.fullscreenElement||document.webkitFullscreenElement||null;}
function syncFullscreenButton(){$('fullscreenBtn').classList.toggle('active',!!fullscreenElement());$('fullscreenBtn').title=fullscreenElement()?'Avslutt fullskjerm':'Fullskjerm';}
async function toggleFullscreen(){try{if(fullscreenElement()){const exit=document.exitFullscreen||document.webkitExitFullscreen;if(exit)await exit.call(document);return;}const root=document.documentElement,request=root.requestFullscreen||root.webkitRequestFullscreen;if(!request){toast('Safari: bruk Del → Legg til på Hjem-skjermen for fullskjerm.',3600);return;}await request.call(root,{navigationUI:'hide'});}catch{toast('Fullskjerm ble avvist. Prøv Del → Legg til på Hjem-skjermen.',3600);}finally{syncFullscreenButton();}}
function toast(text,ms=2200){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),ms);}
function tone(freq=440,dur=.09,type='square',vol=.035){if(!game.sound)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur);}catch{}}
function fanfare(){[392,523,659,784].forEach((n,i)=>setTimeout(()=>tone(n,.18,'square',.05),i*120));}

let dialogDone=null;
function showDialog(speaker,text,portrait='💬',done=null){game.mode='dialog';$('speaker').textContent=speaker;$('dialogText').textContent=text;$('portrait').textContent=portrait;dialogDone=done;show('dialog');tone(260,.04,'square',.018);}
function advanceDialog(){if(game.mode!=='dialog')return;hide('dialog');const cb=dialogDone;dialogDone=null;game.mode='world';if(cb)setTimeout(cb,30);}

function creatureThumb(c){return`<div class="creature-icon" style="background:${c.colors[2]}"><img src="assets/creatures/${c.id}.svg" alt="Illustrasjon av ${c.name}" draggable="false" onerror="this.className='broken'"><span class="creature-fallback">${C.TYPES[c.type].icon}</span></div>`;}
function renderBestiary(){const signature=`${game.seen.join(',')}|${game.caught.join(',')}`;if(signature===bestiarySignature)return;bestiarySignature=signature;$('bestiaryList').innerHTML=Object.values(C.CREATURES).map((c,i)=>{const discovered=game.seen.includes(c.id),friend=game.caught.includes(c.id);if(!discovered)return`<article class="bestiary-card unknown" data-slot="${i}"><div class="bestiary-silhouette">?</div><div><b>Ukjent spor</b><small>Ikke oppdaget</small></div></article>`;return`<article class="bestiary-card ${friend?'friend':''} ${c.legendary?'legendary':''}" data-slot="${i}">${creatureThumb(c)}<div><b>${c.name}</b><small>${C.TYPES[c.type].icon} ${c.type} · ${c.role} · ${c.bio}</small><small class="status">${friend?'★ VENN':'◉ OPPDAGET'}</small></div></article>`;}).join('');}
function updatePanels(){
 const area=areaAt(game.player.x);$('areaLabel').textContent=area==='camp'?'Furuly Camping':area==='forest'?'Hviskeskogen':'Glødesteinshulen';
 const caughtWild=game.caught.filter(id=>id!=='mosemurr'&&id!=='flammefyrsten').length;
 const bossFriend=game.caught.includes('flammefyrsten');
 const questText=game.bossDefeated?(bossFriend?'Historien fullført · Fjellvenn':'Historien fullført · Fjellet er reddet'):game.quest===0?'Snakk med Bestemor Tora':game.quest===1?`Fang villvesener (${Math.min(caughtWild,2)}/2)`:game.quest===2?'Finn Flammefyrsten i hulen':'Utforsk Villspor';
 $('questShort').textContent=questText;
 $('seenCount').textContent=game.seen.length;$('caughtCount').textContent=game.caught.length;$('berryCount').textContent=game.inventory.berries;$('relicCount').textContent=game.relics.length;renderBestiary();
 const signature=[...game.team,...game.reserve].map(u=>`${u.id}:${u.level}:${u.hp}:${u.xp}`).join('|')+`/${game.team.map(u=>u.id).join(',')}`;if(signature!==panelSignature){panelSignature=signature;
 $('teamList').innerHTML=game.team.map((u,i)=>{const c=C.CREATURES[u.id];return`<div class="creature-card">${creatureThumb(c)}<div><b>${i===0?'★ ':''}${c.name}</b> · Lv.${u.level}<small>${c.bio}</small><small class="move-list">${c.role} · ${c.moves.map((m,j)=>j<2||u.level>=3?C.MOVES[m].name:`🔒 ${C.MOVES[m].name} Lv.3`).join(' · ')}</small><div class="hpbar"><i style="width:${100*u.hp/u.maxHp}%"></i></div><small>${u.hp}/${u.maxHp} HP · ${u.xp}/${C.xpNeeded(u.level)} XP</small></div><div><span class="type type-${c.type.toLowerCase()}">${c.type}</span>${i?`<button class="swap-mini" data-leader="${i}">LEDER</button>`:''}</div></div>`}).join('')||'<p>Ingen vesener i flokken.</p>';
 $('reserveList').innerHTML=game.reserve.map((u,i)=>{const c=C.CREATURES[u.id];return`<div class="creature-card">${creatureThumb(c)}<div><b>${c.name}</b> · Lv.${u.level}<small>${u.hp}/${u.maxHp} HP · venter ved leiren</small></div><button class="swap-mini" data-reserve="${i}">BYTT INN</button></div>`}).join('')||'<p class="panel-hint">Ingen vesener venter ved leiren ennå.</p>';
 document.querySelectorAll('[data-leader]').forEach(b=>b.onclick=()=>setLeader(Number(b.dataset.leader)));document.querySelectorAll('[data-reserve]').forEach(b=>b.onclick=()=>bringReserve(Number(b.dataset.reserve)));}
 const quests=[['Møt Bestemor Tora',game.quest>0],['Bli venn med to villvesener',caughtWild>=2],['Åpne fjellporten',game.quest>=2],['Hovedhistorien: Stans Flammefyrsten',game.bossDefeated],[`Valgfritt: Finn tre glødespor (${game.relics.length}/3)`,game.relics.length===3]];quests.push([game.sideQuests.loke==='done'?'Sideoppdrag: Fjordfnuggets blå dun':'Sideoppdrag: Finn og bli venn med Fjordfnugg',game.sideQuests.loke==='done',game.sideQuests.loke==='active']);quests.push([game.sideQuests.siv==='done'?'Sideoppdrag: Naturkretsen er samlet':'Sideoppdrag: Samle ild, vekst og vann',game.sideQuests.siv==='done',game.sideQuests.siv==='active']);quests.push([game.secrets.includes('stjernestein')?'Hemmelighet: Stjernesteinen funnet':'Valgfritt: Følg det blå glimtet i hulen',game.secrets.includes('stjernestein'),false]);quests.push([game.trial.completed?'Postgame: Sporprøven fullført':'Postgame: Sporprøven ved leiren',game.trial.completed,game.bossDefeated&&!game.trial.completed]);if(game.bossDefeated)quests.push([bossFriend?'Flammefyrsten ble en fjellvenn':'Valgfritt: Vennskapsprøven ved fjellets hjerte',bossFriend]);
 $('questList').innerHTML=quests.map(([q,d,a],i)=>`<div class="quest ${d?'done':(a||(!d&&quests.slice(0,i).every(x=>x[1]))?'active':'')}">${d?'✓':'○'} ${q}</div>`).join('');
}
function setLeader(i){if(i<=0||i>=game.team.length)return;game.team.unshift(game.team.splice(i,1)[0]);updatePanels();saveGame();toast(`${C.CREATURES[game.team[0].id].name} leder flokken.`);}
function bringReserve(i){if(i<0||i>=game.reserve.length||!game.team.length)return;const incoming=game.reserve[i],outgoing=game.team[0];game.reserve.splice(i,1,outgoing);game.team[0]=incoming;updatePanels();saveGame();toast(`${C.CREATURES[incoming.id].name} blir med. ${C.CREATURES[outgoing.id].name} hviler ved leiren.`);}
function openPanel(id){if(game.mode!=='world')return;hide('teamPanel');hide('questPanel');show(id);game.mode='panel';tone(520,.05);}
function closePanels(){hide('teamPanel');hide('questPanel');if(game.mode==='panel')game.mode='world';}

function hash(x,y){let h=(x*374761393+y*668265263)^0x5bd1e995;h=(h^(h>>13))*1274126177;return(h^(h>>16))>>>0;}
function areaAt(px){const tx=px/TILE;return tx<14?'camp':tx<29?'forest':'cave';}
function blocked(px,py){const x=Math.floor(px/TILE),y=Math.floor(py/TILE);if(x<1||y<1||x>=WORLD.w-1||y>=WORLD.h-1)return true;
 if(x===29&&y>=1&&y<=26&&!(y>=13&&y<=15))return true;
 if(x>=14&&x<29){const path=y>=13&&y<=15;const clear=(x>20&&x<25&&y>7&&y<12);if(!path&&!clear&&hash(x,y)%5===0)return true;}
 if(x>=30){if(y<6||y>22)return true;if((y===7||y===21)&&x>31&&hash(x,y)%2===0)return true;}
 if(x<14){if((x===2||x===11)&&y>4&&y<10)return true;}
 for(const p of PROPS){if(['tent','camper','stone'].includes(p.kind)&&Math.abs(px-(p.x+.5)*TILE)<22&&Math.abs(py-(p.y+.5)*TILE)<19)return true;}
 return false;
}
function tryMove(dx,dy,dt){if(game.mode!=='world')return;const p=game.player,dist=p.speed*dt;let nx=p.x+dx*dist,ny=p.y+dy*dist;const r=10;
 if(!blocked(nx-r,p.y)&&!blocked(nx+r,p.y))p.x=nx;if(!blocked(p.x,ny-r)&&!blocked(p.x,ny+r))p.y=ny;
 if(dx||dy){p.dir=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');game.trail.push({x:p.x,y:p.y});if(game.trail.length>18)game.trail.shift();const old={x:game.ninni.x,y:game.ninni.y};const target=game.trail[Math.max(0,game.trail.length-13)];if(target){game.ninni.x+=(target.x-game.ninni.x)*Math.min(1,dt*8);game.ninni.y+=(target.y-game.ninni.y)*Math.min(1,dt*8);}const moved=Math.hypot(p.x-old.x,p.y-old.y);game.moved+=dist;game.encounterCooldown-=dist;checkAreaGate();if(game.encounterCooldown<=0)maybeEncounter();}
}
function checkAreaGate(){if(game.player.x>28.7*TILE&&game.caught.length-1<2){game.player.x=28.55*TILE;showDialog('Ninni','Voff! Fjellporten svarer ikke ennå. Vi trenger vennskapet til minst to villvesener.','🐶');}
 if(game.player.x>29.2*TILE&&game.quest<2&&game.caught.length-1>=2){game.quest=2;toast('Fjellporten åpnet seg!');fanfare();updatePanels();saveGame();}
}
function maybeEncounter(){game.encounterCooldown=130+Math.random()*100;const area=areaAt(game.player.x);if(!encounters[area]||Math.random()>.28||game.mode!=='world')return;const pool=encounters[area];const id=pool[Math.floor(Math.random()*pool.length)];startBattle(id,Math.min(4,1+Math.floor((game.caught.length-1)/2)),false);}
function nearestNPC(){let best=null,bd=58;for(const n of NPCS){const d=Math.hypot(game.player.x-n.x,game.player.y-n.y);if(d<bd){best=n;bd=d;}}return best;}
function interact(){if(game.mode==='dialog')return advanceDialog();if(game.mode==='battle'||game.mode==='ending')return;if(game.mode==='panel')return closePanels();if(game.mode!=='world')return;
 const relic=RELICS.find(r=>!game.relics.includes(r.id)&&Math.hypot(game.player.x-(r.x+.5)*TILE,game.player.y-(r.y+.5)*TILE)<58);if(relic){collectRelic(relic);return;}
 const secret=SECRETS.find(s=>!game.secrets.includes(s.id)&&Math.hypot(game.player.x-(s.x+.5)*TILE,game.player.y-(s.y+.5)*TILE)<58);if(secret){collectSecret(secret);return;}
 const n=nearestNPC();if(n){talkNPC(n);return;}
 if(game.bossDefeated&&Math.hypot(game.player.x-(TRIAL.x+.5)*TILE,game.player.y-(TRIAL.y+.5)*TILE)<58){showDialog('Sporsteinen',game.trial.completed?'Sporprøven våkner igjen. Tre kamper, ingen hvile mellom rundene. To villbær venter om flokken står løpet ut.':'Tre naturspor våkner i steinen. Overlev tre kamper uten hvile og vinn fem villbær. Roglasset kan brukes til å avbryte.','◆',startTrial);return;}
 const fire=PROPS.find(p=>p.kind==='fire');if(Math.hypot(game.player.x-(fire.x+.5)*TILE,game.player.y-(fire.y+.5)*TILE)<62){healTeam();showDialog('Leirbålet','Flokken hviler ved varmen. Alle får full energi.','🔥',()=>saveGame(true));return;}
 if(game.player.x>36*TILE&&game.player.y>9*TILE&&game.player.y<19*TILE){if(game.caught.includes('flammefyrsten')){showDialog('Flammefyrsten','Fjellvokteren senker hodet mot Ninni. Glørne er varme, men fredelige.','🔥');return;}if(game.caught.length-1<2){toast('Flammefyrsten er for mektig. Finn flere venner først.');return;}startBattle('flammefyrsten',4,true,game.bossDefeated);return;}
 toast('Ninni snuser etter spor …');tone(700,.04);
}
function collectRelic(relic){game.relics.push(relic.id);game.inventory.berries++;const complete=game.relics.length===3,active=game.team.find(u=>u.hp>0);if(active)C.gainXp(active,12);fanfare();updatePanels();saveGame();showDialog('Glødesporet',complete?'Alle tre sporene synger sammen. Roglasset blir sterkere, og Ninni finner tre ekstra villbær!':'Et gammelt lys fester seg i Roglasset. Fangstsansen blir litt sterkere. Du finner også et villbær.','✦',()=>{if(complete){game.inventory.berries+=3;updatePanels();saveGame();toast('Ninnis sporsans er fulladet!');}});}
function collectSecret(secret){if(game.secrets.includes(secret.id))return;game.secrets.push(secret.id);game.inventory.berries+=3;const active=game.team[0],before=active?.level||0;if(active)C.gainXp(active,30);const learned=before<3&&active?.level>=3?` ${C.CREATURES[active.id].name} lærer ${C.MOVES[C.CREATURES[active.id].moves[2]].name}!`:'';fanfare();updatePanels();saveGame();showDialog('Stjernesteinen',`Bak en sprekk Ninni oppdaget ligger et kaldt blått stjernelys. Flokken får 30 XP og tre villbær.${learned}`,'✧');}
function startTrial(){if(game.trial.active)return;game.trial.active=true;game.trial.wins=0;game.trial.runs++;for(const u of game.team)u.status={guard:0,weaken:0};startTrialRound();}
function startTrialRound(){const round=game.trial.wins,id=TRIAL.enemies[round];startBattle(id,3+round,false);game.battle.trial=true;game.battle.log=`Sporprøven ${round+1}/3: ${C.CREATURES[id].name}.${game.team.some(u=>u.id==='flammefyrsten')?' Flammefyrsten svarer med et stolt vingeslag.':''}`;renderBattleUI();}
function advanceTrial(){hide('battleUI');game.battle=null;if(game.trial.wins>=3){const first=!game.trial.completed,reward=first?5:2;game.trial.active=false;game.trial.completed=true;game.inventory.berries+=reward;game.mode='world';fanfare();updatePanels();saveGame();showDialog('Sporprøven',`Flokken holdt sammen gjennom alle tre sporene. Ninni finner ${reward} villbær ved steinen${first?' og et nytt merke føres i Reisedagboken':''}.`,'◆');return;}game.mode='world';setTimeout(startTrialRound,260);}
function abortTrial(){if(!game.trial.active)return;hide('battleUI');game.battle=null;game.trial.active=false;game.trial.wins=0;game.mode='world';saveGame();toast('Sporprøven ble avsluttet. Fremgangen i eventyret er trygg.');}
function sideQuestReady(id){if(id==='loke')return game.caught.includes('fjordfnugg');if(id==='siv')return['ILD','VEKST','VANN'].every(type=>game.caught.some(cid=>C.CREATURES[cid]?.type===type));return false;}
function completeSideQuest(id,n){if(game.sideQuests[id]==='done')return;game.sideQuests[id]='done';const active=game.team[0],before=active?.level||0,reward=id==='loke'?{berries:3,xp:24}:{berries:2,xp:38};game.inventory.berries+=reward.berries;const levels=active?C.gainXp(active,reward.xp):[];const unlocked=before<3&&active?.level>=3?` ${C.CREATURES[active.id].name} lærer ${C.MOVES[C.CREATURES[active.id].moves[2]].name}!`:'';updatePanels();saveGame();fanfare();showDialog(n.name,id==='loke'?`Du fant Fjordfnugg-sporet! Ninni får ${reward.berries} villbær, og flokklederen får ${reward.xp} XP.${unlocked}`:`Ild, vekst og vann går sammen i en naturkrets. Flokklederen får ${reward.xp} XP og ${reward.berries} villbær.${unlocked}`,n.icon);}
function handleSideQuest(n){const state=game.sideQuests[n.id];if(!state||state==='done')return false;if(sideQuestReady(n.id)){completeSideQuest(n.id,n);return true;}if(state==='available'){game.sideQuests[n.id]='active';updatePanels();saveGame();showDialog(n.name,n.id==='loke'?'Et Fjordfnugg mistet et blått dun øst i skogen. Kan Ninni finne vesenet og bli venn med det? Jeg har tre villbær til den som lykkes.':'Skogen trenger balanse. Bli venn med minst ett ild-, vekst- og vannvesen, så lærer flokken å kjempe som en naturkrets.',n.icon);return true;}showDialog(n.name,n.id==='loke'?'Fjordfnugg følger bekken og vinden. Se etter det blå sporet i den østlige skogen.':'Naturkretsen mangler fortsatt en type. Sjekk Sporboka: ild, vekst og vann må alle være venner.',n.icon);return true;}
function talkNPC(n){const bossFriend=game.caught.includes('flammefyrsten');if(n.id!=='tora'&&handleSideQuest(n))return;if(n.id==='tora'){showDialog(n.name,bossFriend?'Ninni kom hjem med selveste fjellvokteren i hælene! Flammefyrsten valgte dere – det vennskapet skal leiren huske.':game.bossDefeated?'Dere stilnet fjellets sinne. Fyrsten vokter fortsatt hjertet der inne, og Ninni kan lede dere tilbake når dere er klare.':game.quest===0?'Ninni fant Mosemurr ved bobilen. Ta vare på hverandre og følg sporene østover.':'Roglasset virker best når vesenet har lite energi igjen. Leirbålet helbreder hele flokken.',n.icon);}
 if(n.id==='loke')showDialog(n.name,bossFriend?'Jeg hørte vingeslag over hele campingen! Tenk at Flammefyrsten faktisk følger flokken deres.':game.bossDefeated?'Flammene over fjellet er rolige nå. Jeg visste Ninni kunne finne veien hjem igjen!':game.dialogs.loke?'Jeg så et blått fjordfnugg mellom tretoppene!':'Hør! Skogen lager sin egen melodi. Trykk F for å se flokken din.',n.icon,()=>{game.dialogs.loke=true;saveGame();});
 if(n.id==='siv')showDialog(n.name,bossFriend?'Fjellet valgte vennskap fremfor frykt. Sporboka deres forteller nå alle sju historiene.':game.bossDefeated?'Hovedhistorien er fullført, men skogen har fortsatt venner dere ikke har møtt.':'Ild slår vekst, vekst slår vann, og vann slår ild. Ingen type er alltid sterkest.',n.icon,()=>{game.dialogs.siv=true;saveGame();});
}
function healTeam(){for(const u of game.team)u.hp=u.maxHp;updatePanels();tone(523,.12,'sine');}

function startBattle(id,level=1,boss=false,rematch=false){if(game.mode==='battle')return;const enemy=C.makeCreature(id,level),isBoss=boss||!!C.CREATURES[id].boss;if(isBoss){enemy.maxHp+=28;enemy.hp=enemy.maxHp;}game.seen=[...new Set([...game.seen,id])];game.battle={enemy,active:Math.max(0,game.team.findIndex(u=>u.hp>0)),boss:isBoss,rematch,locked:false,round:0,fx:{kind:'enter',target:'enemy',until:performance.now()+420},log:rematch?'Flammefyrsten venter ved fjellets hjerte. Vennskapsprøven begynner på nytt!':`${boss?'Fjellet rister! ':'Et vilt '}${C.CREATURES[id].name} viser seg!`};game.mode='battle';show('battleUI');closePanels();renderBattleUI();tone(boss?110:220,.25,'sawtooth',.05);updatePanels();}
function captureOdds(unit){return C.clamp(C.captureChance(unit)+game.relics.length*.05,0,.95);}
function currentBossFriendship(){const b=game.battle;return b?.boss?C.bossFriendshipState(b.enemy,game.relics.length,game.caught.includes('flammefyrsten')):'not-boss';}
function renderBattleUI(){const b=game.battle;if(!b)return;const p=game.team[b.active],e=b.enemy,pc=C.CREATURES[p.id],ec=C.CREATURES[e.id];const ps=[p.status.guard?'🛡️ Skjold':'',p.status.weaken?'⬇️ Svekket':''].filter(Boolean).join(' · '),es=[e.status.guard?'🛡️ Skjold':'',e.status.weaken?'⬇️ Svekket':''].filter(Boolean).join(' · ');$('battleStatus').innerHTML=`<div><b>${pc.name}</b> Lv.${p.level}<div class="hpbar"><i style="width:${100*p.hp/p.maxHp}%"></i></div>${p.hp}/${p.maxHp} HP <small>${ps}</small></div><div><b>${ec.name}</b> Lv.${e.level}<div class="hpbar"><i style="width:${100*e.hp/e.maxHp}%"></i></div>${e.hp}/${e.maxHp} HP <small>${es}</small></div>`;$('battleLog').textContent=b.log;const moves=pc.moves,unlocked=C.unlockedMoveIds(p);for(let i=0;i<3;i++){const btn=$(`move${i+1}Btn`),move=C.MOVES[moves[i]],open=unlocked.includes(moves[i]);btn.textContent=open?`${C.TYPES[move.type].icon} ${move.name}`:`🔒 ${move.name} Lv.3`;btn.disabled=b.locked||!open;}const bossState=currentBossFriendship(),capture=$('captureBtn'),bossLabels={'missing-relics':'✦ FINN 3 SPOR',weaken:'🔥 SVEKK MER',ready:'🧿 FJELLROGLAS',already:'★ ALLEREDE VENN'};if(b.trial){capture.disabled=b.locked;capture.textContent='↩ AVBRYT PRØVE';capture.dataset.state='trial';capture.classList.remove('ready');}else{capture.disabled=b.locked||(b.boss&&bossState!=='ready');capture.textContent=b.boss?bossLabels[bossState]:`🧿 ROGLAS ${Math.round(captureOdds(e)*100)}%`;capture.dataset.state=b.boss?bossState:'wild';capture.classList.toggle('ready',bossState==='ready');}$('itemBtn').textContent=`🫐 VILLBÆR ×${game.inventory.berries}`;$('itemBtn').disabled=b.locked||game.inventory.berries<1||p.hp>=p.maxHp;$('switchBtn').disabled=b.locked||game.team.filter(u=>u.hp>0).length<2;}
function setBattleLog(text){if(!game.battle)return;game.battle.log=text;$('battleLog').textContent=text;}
function playerMove(moveIndex){const b=game.battle;if(!b||b.locked)return;const unit=game.team[b.active];const move=C.CREATURES[unit.id].moves[moveIndex];if(!C.unlockedMoveIds(unit).includes(move))return;b.locked=true;const r=C.applyMove(unit,b.enemy,move,.82+Math.random()*.18);b.fx={kind:r.mult>1?'burst':'hit',target:'enemy',until:performance.now()+420};tone(r.mult>1?690:460,.09,'square',.045);setBattleLog(`${C.CREATURES[unit.id].name} brukte ${r.move.name}! ${r.mult>1?'Det traff ekstra hardt! ':r.mult<1?'Ikke særlig effektivt. ':''}−${r.damage} HP`);renderBattleUI();setTimeout(()=>{if(b.enemy.hp<=0)return winBattle();enemyTurn();},650);}
function enemyTurn(){const b=game.battle;if(!b)return;const enemy=b.enemy,unit=game.team[b.active];const move=C.chooseEnemyMove(enemy,unit,Math.random());const r=C.applyMove(enemy,unit,move,.78+Math.random()*.19);b.fx={kind:r.mult>1?'burst':'hit',target:'player',until:performance.now()+420};tone(150,.12,'sawtooth',.045);setBattleLog(`${C.CREATURES[enemy.id].name} svarer med ${r.move.name}. −${r.damage} HP`);C.tickStatus(enemy);C.tickStatus(unit);renderBattleUI();setTimeout(()=>{if(unit.hp<=0){const next=game.team.findIndex((u,i)=>i!==b.active&&u.hp>0);if(next<0)return loseBattle();b.active=next;setBattleLog(`${C.CREATURES[unit.id].name} må hvile. ${C.CREATURES[game.team[next].id].name} tar over!`);}b.round++;b.locked=false;renderBattleUI();},650);}
function attemptCapture(){const b=game.battle;if(!b||b.locked)return;if(b.trial){abortTrial();return;}if(b.boss){const state=currentBossFriendship();if(state!=='ready'){setBattleLog(state==='missing-relics'?'Fjellroglasset trenger alle tre glødesporene.':'Flammefyrsten må svekkes mer før den vil lytte.');return;}b.locked=true;b.fx={kind:'capture',target:'enemy',until:performance.now()+1000};tone(940,.18,'sine');setBattleLog('Tre glødespor møtes i Fjellroglasset. Ninni står rolig og venter …');renderBattleUI();setTimeout(befriendBoss,1000);return;}b.locked=true;b.fx={kind:'capture',target:'enemy',until:performance.now()+750};tone(820,.12,'sine');setBattleLog('Roglasset tegner en lysende ring rundt vesenet …');renderBattleUI();setTimeout(()=>{if(Math.random()<captureOdds(b.enemy))captureSuccess();else{setBattleLog(`${C.CREATURES[b.enemy.id].name} brøt ut av lysringen!`);setTimeout(enemyTurn,500);}},750);}
function befriendBoss(){const b=game.battle;if(!b||!b.boss||currentBossFriendship()!=='ready')return;if(!game.caught.includes('flammefyrsten'))game.caught.push('flammefyrsten');const friend=C.makeCreature('flammefyrsten',3);if(game.team.length<3){game.team.push(friend);setBattleLog('Flammefyrsten senker kronen. Den velger å følge Ninni og blir med i flokken!');}else{game.reserve.push(friend);setBattleLog('Flammefyrsten senker kronen. Den velger vennskapet og venter ved leiren!');}game.bossDefeated=true;game.endingType='befriended';game.quest=3;fanfare();updatePanels();setTimeout(()=>finishGame('befriended'),1400);}
function useBerry(){const b=game.battle;if(!b||b.locked||game.inventory.berries<1)return;const unit=game.team[b.active];if(unit.hp>=unit.maxHp)return;b.locked=true;game.inventory.berries--;const heal=Math.max(12,Math.round(unit.maxHp*.36));unit.hp=C.clamp(unit.hp+heal,0,unit.maxHp);b.fx={kind:'heal',target:'player',until:performance.now()+520};tone(660,.2,'sine',.05);setBattleLog(`${C.CREATURES[unit.id].name} spiser et villbær og får ${heal} HP.`);updatePanels();renderBattleUI();setTimeout(enemyTurn,650);}
function captureSuccess(){const b=game.battle,id=b.enemy.id,c=C.CREATURES[id],isNew=!game.caught.includes(id);if(isNew)game.caught.push(id);const friend={...b.enemy,hp:Math.max(1,b.enemy.hp),status:{guard:0,weaken:0}};if(game.team.length<3){game.team.push(friend);setBattleLog(`${c.name} ble med i flokken!`);}else if(isNew){game.reserve.push(friend);setBattleLog(`${c.name} ble med og venter trygt ved leiren.`);}else setBattleLog(`${c.name} stoler allerede på dere. Flokken på tre er full.`);fanfare();if(game.caught.length-1>=2&&game.quest<2)game.quest=2;setTimeout(()=>endBattle('capture'),950);}
function switchUnit(){const b=game.battle;if(!b||b.locked)return;const alive=game.team.map((u,i)=>u.hp>0?i:-1).filter(i=>i>=0&&i!==b.active);if(!alive.length)return;b.active=alive[0];b.locked=true;setBattleLog(`${C.CREATURES[game.team[b.active].id].name}, din tur!`);renderBattleUI();setTimeout(enemyTurn,500);}
function winBattle(){const b=game.battle,unit=game.team[b.active],xp=b.boss?80:22+b.enemy.level*8,before=unit.level;const levels=C.gainXp(unit,xp),learned=before<3&&unit.level>=3?` Nytt angrep: ${C.MOVES[C.CREATURES[unit.id].moves[2]].name}!`:'';setBattleLog(`${C.CREATURES[b.enemy.id].name} roer seg. ${C.CREATURES[unit.id].name} får ${xp} XP.${levels.length?' Nytt nivå: '+unit.level+'!':''}${learned}`);fanfare();if(b.trial){game.trial.wins++;setTimeout(advanceTrial,900);return;}if(b.boss){game.bossDefeated=true;game.endingType='defeated';game.quest=3;setTimeout(()=>finishGame('defeated'),1100);}else setTimeout(()=>endBattle('win'),950);}
function loseBattle(){const wasTrial=!!game.battle?.trial;setBattleLog(wasTrial?'Sporprøven brytes. Ninni leder den utslitte flokken tilbake til bålet.':'Flokken er utslitt. Ninni løper tilbake til leirbålet!');tone(110,.4,'sawtooth');setTimeout(()=>{if(wasTrial){game.trial.active=false;game.trial.wins=0;}healTeam();game.player.x=9*TILE;game.player.y=17*TILE;endBattle('lose');toast(wasTrial?'Sporprøven kan forsøkes igjen.':'Bestemor Tora hjalp flokken på beina igjen.');},1200);}
function endBattle(reason){hide('battleUI');game.battle=null;game.mode='world';game.encounterCooldown=110;updatePanels();saveGame();if(reason==='capture')toast('Nytt vennskap registrert i reisedagboken!');}
function finishGame(type=game.endingType||'defeated'){game.endingType=type;const time=elapsedSeconds();game.elapsed=time;if(!game.best||time<game.best){game.best=time;localStorage.setItem(BEST_KEY,String(time));}hide('battleUI');game.battle=null;game.mode='ending';const befriended=type==='befriended';$('endingTitle').textContent=befriended?'EN NY FJELLVENN':'FJELLET PUSTER IGJEN';$('endingText').textContent=befriended?'Tre glødespor samles i Fjellroglasset. Ninni blir stående uten frykt. Flammefyrsten senker kronen og velger selv å følge flokken som fjellets venn.':'Ninni finner glødesteinen under Flammefyrstens klo. Når steinen legges tilbake i fjellets hjerte, dempes flammene. Fyrsten blir igjen som vokter – rolig, men fortsatt fri.';$('endingStats').innerHTML=`<p><b>Tid:</b> ${formatTime(time)} · <b>Oppdaget:</b> ${game.seen.length}/7 · <b>Venner:</b> ${game.caught.length}/7</p><p>${befriended?'Flammefyrsten venter i flokken eller leirreserven.':'Vennskapsprøven kan forsøkes igjen ved fjellets hjerte.'}</p><p>Beste tid: ${formatTime(game.best)}</p>`;show('ending');fanfare();updatePanels();saveGame();}
function formatTime(sec){sec=Math.max(0,Math.floor(sec||0));return`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;}

function pause(){if(game.mode==='world'){game.mode='pause';show('pauseScreen');}else if(game.mode==='pause'){hide('pauseScreen');game.mode='world';last=performance.now();}}
function actionKey(code){if(code==='Enter'||code==='KeyE'||code==='Space')interact();if(code==='KeyF')visible('teamPanel')?closePanels():openPanel('teamPanel');if(code==='KeyQ')visible('questPanel')?closePanels():openPanel('questPanel');if(code==='KeyP'||code==='Escape'){if(game.mode==='panel')closePanels();else pause();}}
function bindControls(){
 addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(!e.repeat)actionKey(e.code);});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.mode==='world')pause();});
 const touchPointers=new Map();const releaseDirection=(pointerId)=>{const active=touchPointers.get(pointerId);if(!active)return;touchPointers.delete(pointerId);keys.delete(active.code);active.btn.classList.remove('pressed');try{if(active.btn.hasPointerCapture?.(pointerId))active.btn.releasePointerCapture(pointerId);}catch{}};
 document.querySelectorAll('[data-dir]').forEach(btn=>{const code={up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight'}[btn.dataset.dir];btn.draggable=false;btn.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();releaseDirection(e.pointerId);touchPointers.set(e.pointerId,{code,btn});keys.add(code);btn.classList.add('pressed');try{btn.setPointerCapture?.(e.pointerId);}catch{}},{passive:false});btn.addEventListener('pointermove',e=>{if(!touchPointers.has(e.pointerId))return;const r=btn.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)releaseDirection(e.pointerId);},{passive:false});for(const type of ['pointerup','pointercancel','lostpointercapture','pointerleave'])btn.addEventListener(type,e=>{e.preventDefault();releaseDirection(e.pointerId);},{passive:false});for(const type of ['contextmenu','selectstart','dragstart'])btn.addEventListener(type,e=>e.preventDefault());});
 for(const type of ['pointerup','pointercancel'])document.addEventListener(type,e=>releaseDirection(e.pointerId),{passive:true});$('mobileControls').addEventListener('contextmenu',e=>e.preventDefault());
 $('fullscreenBtn').onclick=toggleFullscreen;document.addEventListener('fullscreenchange',syncFullscreenButton);document.addEventListener('webkitfullscreenchange',syncFullscreenButton);
 $('actionBtn').onclick=interact;$('dialog').onclick=interact;$('mobileTeam').onclick=()=>openPanel('teamPanel');$('mobileQuest').onclick=()=>openPanel('questPanel');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closePanels);
 $('move1Btn').onclick=()=>playerMove(0);$('move2Btn').onclick=()=>playerMove(1);$('move3Btn').onclick=()=>playerMove(2);$('captureBtn').onclick=attemptCapture;$('itemBtn').onclick=useBerry;$('switchBtn').onclick=switchUnit;
 $('newGameBtn').onclick=()=>{if(hasSave()&&!confirm('Starte på nytt og overskrive lagringen?'))return;resetGame();};$('continueBtn').onclick=()=>{if(loadGame()){hide('titleScreen');toast('Velkommen tilbake til Villspor');}};
 $('saveBtn').onclick=()=>saveGame(true);$('resumeBtn').onclick=pause;$('keepPlayingBtn').onclick=()=>{hide('ending');game.mode='world';game.player.x=32*TILE;game.player.y=14*TILE;};$('restartBtn').onclick=resetGame;$('soundBtn').onclick=()=>{game.sound=!game.sound;$('soundBtn').textContent=game.sound?'🔊':'🔇';if(game.sound)tone(520,.08);saveGame();};
}

function drawWorld(){const cam=game.camera;ctx.fillStyle='#5e9860';ctx.fillRect(0,0,canvas.width,canvas.height);const x0=Math.max(0,Math.floor(cam.x/TILE)-1),x1=Math.min(WORLD.w,Math.ceil((cam.x+canvas.width)/TILE)+1),y0=Math.max(0,Math.floor(cam.y/TILE)-1),y1=Math.min(WORLD.h,Math.ceil((cam.y+canvas.height)/TILE)+1);
 for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const sx=x*TILE-cam.x,sy=y*TILE-cam.y;let color=x<14?((x+y)%2?'#78ad68':'#72a763'):x<29?((x+y)%2?'#3f754b':'#467d50'):((x+y)%2?'#4d4e52':'#55565b');if(x>=14&&x<29&&y>=13&&y<=15)color='#a88b5c';if(x>=29&&y>=13&&y<=15)color='#5e5651';ctx.fillStyle=color;ctx.fillRect(sx,sy,TILE+1,TILE+1);if(hash(x,y)%11===0&&x<29){ctx.fillStyle='#bed37a';ctx.fillRect(sx+5,sy+8,3,7);ctx.fillRect(sx+2,sy+10,8,3);}if(x>=29&&hash(x,y)%13===0){ctx.fillStyle='#77777d';ctx.fillRect(sx+4,sy+22,24,4);}}
 drawRegionDetails();drawForestCanopy(x0,x1,y0,y1);for(const p of PROPS)drawProp(p);if(game.bossDefeated)drawTrialStone();for(const r of RELICS)if(!game.relics.includes(r.id))drawRelic(r);for(const s of SECRETS)if(!game.secrets.includes(s.id))drawSecret(s);for(const n of NPCS)drawNPC(n);if(!game.caught.includes('flammefyrsten')&&game.player.x>29*TILE)drawCreature('flammefyrsten',38*TILE-cam.x,14*TILE-cam.y,1.1,false);
 drawNinni();drawPlayer();drawMiniMap();
}
function drawRegionDetails(){const c=game.camera;
 ctx.fillStyle='#335f76';ctx.fillRect(-c.x,24*TILE-c.y,14*TILE,4*TILE);for(let x=0;x<14;x++){ctx.fillStyle=x%2?'#6cc3cf':'#79d1d2';ctx.fillRect(x*TILE-c.x,25*TILE-c.y+Math.sin(performance.now()/300+x)*3,TILE,3);}
 ctx.fillStyle='#28302f';ctx.fillRect(29*TILE-c.x,0-c.y,2*TILE,WORLD.h*TILE);ctx.fillStyle='#7a6b54';ctx.fillRect(29*TILE-c.x,13*TILE-c.y,2*TILE,3*TILE);ctx.fillStyle='#e88745';ctx.fillRect(29*TILE-c.x+13,13*TILE-c.y+12,6,70);
 drawAtmosphere();ctx.fillStyle='#7ac7b4';ctx.font='bold 15px Nunito';ctx.fillText('FURULY CAMPING',2*TILE-c.x,3*TILE-c.y);ctx.fillStyle='#d7d1a7';ctx.fillText('HVISKESKOGEN',18*TILE-c.x,4*TILE-c.y);ctx.fillStyle='#f0a35a';ctx.fillText('GLØDESTEINSHULEN',31*TILE-c.x,5*TILE-c.y);
}
function drawAtmosphere(){const c=game.camera,t=performance.now()/1000;ctx.save();ctx.globalAlpha=.28;ctx.fillStyle='#f5e8a5';for(let i=0;i<4;i++){const x=(15+i*4)*TILE-c.x;ctx.beginPath();ctx.moveTo(x,0-c.y);ctx.lineTo(x+70,0-c.y);ctx.lineTo(x+125,19*TILE-c.y);ctx.lineTo(x+75,19*TILE-c.y);ctx.fill();}ctx.globalAlpha=.75;for(let i=0;i<8;i++){const x=(30+i*1.45)*TILE-c.x,y=(7+(i%4)*4.2)*TILE-c.y;ctx.fillStyle=i%2?'#ff7842':'#ffc04c';ctx.beginPath();ctx.arc(x,y,3+Math.sin(t*3+i),0,7);ctx.fill();}ctx.strokeStyle='#302d33';ctx.lineWidth=8;for(let x=30;x<42;x+=2){ctx.beginPath();ctx.moveTo(x*TILE-c.x,0-c.y);ctx.lineTo((x+.45)*TILE-c.x,(2+(x%3))*TILE-c.y);ctx.stroke();}ctx.restore();}
function drawForestCanopy(x0,x1,y0,y1){const cam=game.camera;for(let y=y0;y<y1;y++)for(let x=Math.max(14,x0);x<Math.min(29,x1);x++){const path=y>=13&&y<=15,clear=x>20&&x<25&&y>7&&y<12;if(path||clear||hash(x,y)%5!==0)continue;const sx=(x+.5)*TILE-cam.x,sy=(y+.6)*TILE-cam.y;ctx.fillStyle='#273f32';ctx.fillRect(sx-5,sy-7,10,25);ctx.fillStyle='#315f3e';ctx.beginPath();ctx.arc(sx,sy-18,20,0,7);ctx.fill();ctx.fillStyle='#54844c';ctx.beginPath();ctx.arc(sx-8,sy-24,11,0,7);ctx.arc(sx+9,sy-21,12,0,7);ctx.fill();}}
function drawTrialStone(){const t=performance.now()/450,x=(TRIAL.x+.5)*TILE-game.camera.x,y=(TRIAL.y+.5)*TILE-game.camera.y;ctx.save();ctx.shadowBlur=game.trial.completed?7:14;ctx.shadowColor='#e8ce68';ctx.fillStyle='#475c54';ctx.beginPath();ctx.moveTo(x-13,y+13);ctx.lineTo(x-9,y-10);ctx.lineTo(x+7,y-15);ctx.lineTo(x+14,y+13);ctx.fill();ctx.strokeStyle='#ffe681';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-5,y+5);ctx.lineTo(x,y-6);ctx.lineTo(x+5,y+5);ctx.stroke();ctx.globalAlpha=.5+.25*Math.sin(t);ctx.fillStyle='#fff2a0';ctx.fillRect(x-2,y-3,4,4);ctx.restore();}
function drawSecret(s){const t=performance.now()/420,x=(s.x+.5)*TILE-game.camera.x,y=(s.y+.5)*TILE-game.camera.y;ctx.save();ctx.shadowBlur=12+Math.sin(t)*4;ctx.shadowColor='#87dfff';ctx.fillStyle='#75bcd0';for(let i=0;i<3;i++){ctx.save();ctx.translate(x+(i-1)*9,y+Math.abs(i-1)*4);ctx.rotate((i-1)*.25);ctx.fillRect(-3,-9,6,14);ctx.restore();}ctx.fillStyle='#d9fbff';ctx.fillRect(x-2,y-7,4,4);ctx.restore();}
function drawRelic(r){const t=performance.now()/280,x=(r.x+.5)*TILE-game.camera.x,y=(r.y+.5)*TILE-game.camera.y,p=4+Math.sin(t+r.x)*2;ctx.fillStyle='#fff6ae33';ctx.beginPath();ctx.arc(x,y,18+p,0,7);ctx.fill();ctx.fillStyle='#ffe477';ctx.beginPath();ctx.moveTo(x,y-12-p);ctx.lineTo(x+7,y);ctx.lineTo(x,y+12+p);ctx.lineTo(x-7,y);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(x-2,y-2,4,4);}
function drawMiniMap(){const x=canvas.width-172,y=18,w=150,h=38;ctx.fillStyle='#071b1acc';ctx.fillRect(x-5,y-5,w+10,h+10);ctx.fillStyle='#78ad68';ctx.fillRect(x,y,50,h);ctx.fillStyle='#467d50';ctx.fillRect(x+50,y,55,h);ctx.fillStyle='#55565b';ctx.fillRect(x+105,y,45,h);ctx.fillStyle='#d8c273';ctx.fillRect(x+50,y+17,100,5);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x+game.player.x/(WORLD.w*TILE)*w,y+game.player.y/(WORLD.h*TILE)*h,4,0,7);ctx.fill();if(!game.caught.includes('flammefyrsten')){ctx.fillStyle='#ff714a';ctx.fillRect(x+135,y+17,6,6);}ctx.strokeStyle='#d9c56b';ctx.strokeRect(x-1,y-1,w+2,h+2);}
function drawProp(p){const x=p.x*TILE-game.camera.x,y=p.y*TILE-game.camera.y;if(p.kind==='tent'){ctx.fillStyle='#e8bd58';ctx.beginPath();ctx.moveTo(x,y+28);ctx.lineTo(x+16,y);ctx.lineTo(x+32,y+28);ctx.fill();ctx.fillStyle='#8d4c38';ctx.fillRect(x+14,y+14,4,14);}if(p.kind==='camper'){ctx.fillStyle='#e9e2c4';ctx.fillRect(x-10,y,65,33);ctx.fillStyle='#3a7180';ctx.fillRect(x+29,y+5,20,11);ctx.fillStyle='#cc6650';ctx.fillRect(x-7,y+5,22,6);ctx.fillStyle='#252e2e';ctx.beginPath();ctx.arc(x+2,y+34,8,0,7);ctx.arc(x+45,y+34,8,0,7);ctx.fill();}if(p.kind==='fire'){ctx.fillStyle='#60402f';ctx.fillRect(x+3,y+23,28,6);ctx.fillStyle='#ffca50';ctx.beginPath();ctx.moveTo(x+16,y+2);ctx.lineTo(x+27,y+25);ctx.lineTo(x+6,y+25);ctx.fill();ctx.fillStyle='#ed663c';ctx.fillRect(x+13,y+13,7,12);}if(p.kind==='sign'){ctx.fillStyle='#6b4c32';ctx.fillRect(x+14,y+12,5,24);ctx.fillStyle='#d5b56b';ctx.fillRect(x-4,y,41,18);ctx.fillStyle='#3f543e';ctx.font='bold 10px sans-serif';ctx.fillText('SKOG →',x,y+12);}if(p.kind==='stone'){ctx.fillStyle='#7c7c79';ctx.beginPath();ctx.ellipse(x+16,y+20,15,11,0,0,7);ctx.fill();}if(p.kind==='crystal'){ctx.fillStyle='#ff9a55';ctx.beginPath();ctx.moveTo(x+16,y);ctx.lineTo(x+28,y+18);ctx.lineTo(x+16,y+33);ctx.lineTo(x+5,y+18);ctx.fill();}}
function drawNPC(n){const x=n.x-game.camera.x,y=n.y-game.camera.y;ctx.fillStyle=n.color;ctx.fillRect(x-10,y-10,20,23);ctx.fillStyle='#f3cc9d';ctx.fillRect(x-7,y-20,14,13);ctx.fillStyle='#172627';ctx.fillRect(x-4,y-17,2,2);ctx.fillRect(x+3,y-17,2,2);ctx.fillStyle='#fff';ctx.font='12px sans-serif';ctx.textAlign='center';ctx.fillText(n.icon,x,y-24);ctx.textAlign='left';}
function drawPlayer(){const x=game.player.x-game.camera.x,y=game.player.y-game.camera.y,step=Math.sin(game.moved*.12)*2;ctx.fillStyle='#102b2a55';ctx.beginPath();ctx.ellipse(x,y+14,14,5,0,0,7);ctx.fill();ctx.fillStyle='#172f3f';ctx.fillRect(x-8,y+5+step,6,10);ctx.fillRect(x+2,y+5-step,6,10);ctx.fillStyle='#264d69';ctx.fillRect(x-10,y-10,20,21);ctx.fillStyle='#d7ad7e';ctx.fillRect(x-8,y-21,16,13);ctx.fillStyle='#d45f42';ctx.fillRect(x-10,y-25,20,7);ctx.fillStyle='#873f32';ctx.fillRect(x-13,y-8,5,15);ctx.fillStyle='#f0d35b';const handX=game.player.dir==='right'?8:-12;ctx.fillRect(x+handX,y-5,4,9);ctx.fillStyle='#1b2d31';ctx.fillRect(x-5,y-17,3,3);ctx.fillRect(x+3,y-17,3,3);}
function drawNinni(){const x=game.ninni.x-game.camera.x,y=game.ninni.y-game.camera.y;ctx.fillStyle='#102b2a44';ctx.beginPath();ctx.ellipse(x,y+9,16,5,0,0,7);ctx.fill();ctx.fillStyle='#f8f3df';for(const [dx,dy,r] of [[-7,-1,9],[1,-3,10],[8,-1,8],[9,-10,8]]){ctx.beginPath();ctx.arc(x+dx,y+dy,r,0,7);ctx.fill();}ctx.fillStyle='#d7cbb2';ctx.beginPath();ctx.ellipse(x+12,y-13,4,8,-.45,0,7);ctx.fill();ctx.fillStyle='#d74d48';ctx.fillRect(x+4,y-5,10,3);ctx.fillStyle='#1d2a29';ctx.fillRect(x+10,y-12,3,3);ctx.fillRect(x+15,y-8,4,3);ctx.strokeStyle='#f8f3df';ctx.lineWidth=5;ctx.beginPath();ctx.arc(x-13,y-8,9,.3,4.9);ctx.stroke();ctx.fillStyle='#eee5ce';ctx.fillRect(x-7,y+5,4,7);ctx.fillRect(x+5,y+5,4,7);}
function drawCreature(id,x,y,scale=1,flip=false){const c=C.CREATURES[id],s=scale,art=creatureArt[id];if(art?.complete&&art.naturalWidth){ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);const size=96*s;ctx.drawImage(art,-size/2,-size*.62,size,size);ctx.restore();return;}ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(0,22*s,25*s,7*s,0,0,7);ctx.fill();const [a,b,d]=c.colors;ctx.fillStyle=a;
 if(c.shape==='fox'){ctx.beginPath();ctx.ellipse(0,0,24*s,18*s,0,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(-18*s,-12*s);ctx.lineTo(-12*s,-32*s);ctx.lineTo(-2*s,-15*s);ctx.moveTo(18*s,-12*s);ctx.lineTo(12*s,-32*s);ctx.lineTo(2*s,-15*s);ctx.fill();ctx.fillStyle=b;ctx.beginPath();ctx.moveTo(-7*s,1*s);ctx.lineTo(7*s,1*s);ctx.lineTo(0,13*s);ctx.fill();}
 else if(c.shape==='moss'){ctx.beginPath();ctx.arc(0,0,26*s,0,7);ctx.fill();ctx.fillStyle=b;for(let i=-2;i<=2;i++){ctx.beginPath();ctx.arc(i*10*s,-20*s,10*s,0,7);ctx.fill();}}
 else if(c.shape==='otter'){ctx.beginPath();ctx.ellipse(0,1*s,17*s,27*s,0,0,7);ctx.fill();ctx.fillStyle=b;ctx.beginPath();ctx.ellipse(0,7*s,10*s,14*s,0,0,7);ctx.fill();}
 else if(c.shape==='crab'){ctx.beginPath();ctx.ellipse(0,2*s,25*s,18*s,0,0,7);ctx.fill();ctx.strokeStyle=b;ctx.lineWidth=7*s;for(const side of [-1,1]){ctx.beginPath();ctx.moveTo(side*17*s,0);ctx.lineTo(side*32*s,-12*s);ctx.stroke();}}
 else if(c.shape==='bird'){ctx.beginPath();ctx.ellipse(0,0,17*s,24*s,0,0,7);ctx.fill();ctx.fillStyle=b;ctx.beginPath();ctx.ellipse(-16*s,2*s,15*s,8*s,-.5,0,7);ctx.ellipse(16*s,2*s,15*s,8*s,.5,0,7);ctx.fill();}
 else if(c.shape==='bat'){ctx.beginPath();ctx.arc(0,0,16*s,0,7);ctx.fill();ctx.fillStyle=b;for(const side of [-1,1]){ctx.beginPath();ctx.moveTo(side*10*s,-8*s);ctx.lineTo(side*35*s,-24*s);ctx.lineTo(side*29*s,8*s);ctx.lineTo(side*12*s,5*s);ctx.fill();}}
 else{ctx.beginPath();ctx.ellipse(0,0,29*s,35*s,0,0,7);ctx.fill();ctx.fillStyle=b;for(const side of [-1,1]){ctx.beginPath();ctx.moveTo(side*12*s,-15*s);ctx.lineTo(side*42*s,-35*s);ctx.lineTo(side*31*s,10*s);ctx.fill();}ctx.fillStyle=d;ctx.beginPath();ctx.moveTo(-12*s,-27*s);ctx.lineTo(-4*s,-48*s);ctx.lineTo(2*s,-29*s);ctx.lineTo(12*s,-49*s);ctx.lineTo(14*s,-23*s);ctx.fill();}
 ctx.fillStyle='#fff';ctx.fillRect(-9*s,-6*s,6*s,7*s);ctx.fillRect(5*s,-6*s,6*s,7*s);ctx.fillStyle=d;ctx.fillRect(-7*s,-4*s,3*s,4*s);ctx.fillRect(7*s,-4*s,3*s,4*s);ctx.restore();}
function drawBattle(){const b=game.battle;if(!b)return;const now=performance.now(),t=now/1000,fx=b.fx&&now<b.fx.until?b.fx:null,shake=fx&&['hit','burst'].includes(fx.kind)?Math.sin(now*.11)*6:0;ctx.save();ctx.translate(shake,0);const sky=ctx.createLinearGradient(0,0,0,canvas.height);if(b.boss){sky.addColorStop(0,'#241827');sky.addColorStop(.62,'#60312f');sky.addColorStop(1,'#bd5336');}else{sky.addColorStop(0,'#9ac8bd');sky.addColorStop(.58,'#c7dba9');sky.addColorStop(1,'#5f9361');}ctx.fillStyle=sky;ctx.fillRect(-10,0,canvas.width+20,canvas.height);ctx.fillStyle=b.boss?'#4a292e':'#477655';for(let i=0;i<12;i++){const x=i*95-20,h=70+(i%3)*25;ctx.beginPath();ctx.moveTo(x,350);ctx.lineTo(x+38,350-h);ctx.lineTo(x+76,350);ctx.fill();}ctx.fillStyle=b.boss?'#783a31':'#6c9d67';for(let i=0;i<14;i++){ctx.beginPath();ctx.arc(i*80+(i%2)*20,390+Math.sin(t+i)*5,55,0,7);ctx.fill();}ctx.fillStyle=b.boss?'#f08045':'#e6d99a';const compact=innerHeight<=650&&innerWidth>innerHeight,enemyY=compact?215:260,playerY=compact?320:380;if(b.boss&&game.relics.length===3){ctx.save();ctx.shadowBlur=currentBossFriendship()==='ready'?24:14;ctx.shadowColor='#ffe873';for(let i=0;i<3;i++){const a=t*1.4+i*Math.PI*2/3,x=710+Math.cos(a)*105,y=enemyY-25+Math.sin(a)*42;ctx.fillStyle=i===0?'#fff3a0':i===1?'#ffb958':'#ffe873';ctx.beginPath();ctx.arc(x,y,currentBossFriendship()==='ready'?8:5,0,7);ctx.fill();}ctx.restore();}ctx.beginPath();ctx.ellipse(710,enemyY+30,145,45,0,0,7);ctx.ellipse(245,playerY+30,165,48,0,0,7);ctx.fill();const enemyKick=fx&&fx.target==='enemy'&&['hit','burst'].includes(fx.kind)?Math.sin(now*.15)*14:0,playerKick=fx&&fx.target==='player'&&['hit','burst'].includes(fx.kind)?Math.sin(now*.15)*14:0;drawCreature(b.enemy.id,710+enemyKick,enemyY,b.boss?2.2:1.8,false);drawCreature(game.team[b.active].id,245+playerKick,playerY,2,true);if(fx){const x=fx.target==='enemy'?710:245,y=fx.target==='enemy'?enemyY-15:playerY-25,color=fx.kind==='heal'?'#8dff9a':fx.kind==='capture'?'#ffe873':'#fff2b0';ctx.strokeStyle=color;ctx.lineWidth=fx.kind==='burst'?8:5;for(let i=0;i<(fx.kind==='burst'?8:4);i++){const a=i*Math.PI/4+t*2,r=28+(fx.until-now)*.08;ctx.beginPath();ctx.moveTo(x+Math.cos(a)*12,y+Math.sin(a)*12);ctx.lineTo(x+Math.cos(a)*r,y+Math.sin(a)*r);ctx.stroke();}if(fx.kind==='capture'){ctx.beginPath();ctx.arc(x,y,45+Math.sin(t*9)*8,0,7);ctx.stroke();}}ctx.fillStyle='#19312f';ctx.font='900 22px Nunito';ctx.fillText(b.boss?'FJELLETS HJERTE':'VILLSPOR',28,42);ctx.restore();}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);if(game.mode==='battle')drawBattle();else drawWorld();}
function update(dt){if(game.mode==='world'){let dx=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0),dy=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0);if(dx&&dy){dx*=.707;dy*=.707;}tryMove(dx,dy,dt);game.camera.x=C.clamp(game.player.x-canvas.width/2,0,WORLD.w*TILE-canvas.width);game.camera.y=C.clamp(game.player.y-canvas.height/2,0,WORLD.h*TILE-canvas.height);if(performance.now()-game.lastSave>30000)saveGame();if(performance.now()-lastPanelUpdate>250){updatePanels();lastPanelUpdate=performance.now();}}}
function loop(ts){const dt=Math.min(.04,(ts-last)/1000||0);last=ts;syncModeUI();update(dt);draw();raf=requestAnimationFrame(loop);}

function init(){bindControls();$('continueBtn').classList.toggle('hidden',!hasSave());$('titleScreen').classList.add('visible');updatePanels();raf=requestAnimationFrame(loop);}
window.VillsporDebug={get game(){return game;},core:C,startBattle,setPosition(x,y){game.player.x=x*TILE;game.player.y=y*TILE;},interact,playerMove,attemptCapture,useBerry,switchUnit,refreshBattle:renderBattleUI,saveGame,loadGame,resetGame,getSnapshot(){return{mode:game.mode,quest:game.quest,team:game.team.map(u=>({id:u.id,level:u.level,hp:u.hp,maxHp:u.maxHp})),reserve:game.reserve.map(u=>({id:u.id,level:u.level,hp:u.hp,maxHp:u.maxHp})),seen:[...game.seen],caught:[...game.caught],relics:[...game.relics],secrets:[...game.secrets],sideQuests:{...game.sideQuests},trial:{...game.trial},inventory:{...game.inventory},bossDefeated:game.bossDefeated,endingType:game.endingType,bossFriendship:currentBossFriendship(),area:areaAt(game.player.x)};},forceWorld(){hide('titleScreen');game.started=true;game.mode='world';game.startTime=game.startTime||Date.now();if(!game.team.length)game.team=[C.makeCreature('mosemurr',1)];},finishGame};
init();
})();
