import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const core=require('./game-core.js');
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const game=fs.readFileSync(new URL('./game.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('./styles.css',import.meta.url),'utf8');
const tests=[];
const test=(name,fn)=>tests.push([name,fn]);

test('datamodellen har seks fangbare originalvesener og én boss',()=>{assert.deepEqual(core.validateData(),[]);assert.equal(Object.values(core.CREATURES).filter(c=>!c.boss).length,6);assert.equal(Object.values(core.CREATURES).filter(c=>c.boss).length,1);});
test('alle vesener har gyldig type og minst to angrep',()=>{for(const c of Object.values(core.CREATURES)){assert.ok(core.TYPES[c.type]);assert.ok(c.moves.length>=2);c.moves.forEach(m=>assert.ok(core.MOVES[m]));}});
test('typesirkelen er ild > vekst > vann > ild',()=>{assert.equal(core.typeMultiplier('ILD','VEKST'),1.5);assert.equal(core.typeMultiplier('VEKST','VANN'),1.5);assert.equal(core.typeMultiplier('VANN','ILD'),1.5);assert.equal(core.typeMultiplier('ILD','VANN'),.67);});
test('kamp gir skade og kan ende i seier',()=>{const a=core.makeCreature('bekkskvett',2),d=core.makeCreature('gnistrev',1);const r=core.applyMove(a,d,'fossedunk',1);assert.ok(r.damage>0);assert.equal(r.mult,1.5);while(d.hp>0)core.applyMove(a,d,'fossedunk',1);assert.equal(d.hp,0);});
test('statusangrep helbreder, beskytter og svekker',()=>{const a=core.makeCreature('mosemurr',2),d=core.makeCreature('bekkskvett',2);a.hp-=12;core.applyMove(a,d,'sporevind',1);assert.ok(a.hp>a.maxHp-12);core.applyMove(d,a,'duggslor',1);assert.ok(d.status.guard>0);core.applyMove(core.makeCreature('gnistrev',2),d,'askesnurr',1);assert.ok(d.status.weaken>0);});
test('fangstsjanse øker når motstanderen svekkes og boss krever særskilt vennskapsprøve',()=>{const u=core.makeCreature('kongleklo',1);const full=core.captureChance(u);u.hp=1;assert.ok(core.captureChance(u)>full);const boss=core.makeCreature('flammefyrsten',4);assert.equal(core.captureChance(boss),0);assert.equal(core.bossFriendshipState(boss,2,false),'missing-relics');assert.equal(core.bossFriendshipState(boss,3,false),'weaken');boss.hp=Math.floor(boss.maxHp*.25);assert.equal(core.bossFriendshipState(boss,3,false),'ready');assert.equal(core.bossFriendshipState(boss,3,true),'already');assert.equal(core.canCapture(u,0),true);});
test('spillbar Flammefyrste er kraftig, men balansert og har to originale angrep',()=>{const u=core.makeCreature('flammefyrsten',3);assert.ok(u.maxHp<90);assert.equal(core.CREATURES.flammefyrsten.moves.length,2);assert.equal(core.CREATURES.flammefyrsten.legendary,true);});
test('erfaring gir nivå og høyere egenskaper',()=>{const u=core.makeCreature('mosemurr',1),old=u.maxHp;const levels=core.gainXp(u,100);assert.ok(levels.length>=1);assert.ok(u.level>1);assert.ok(u.maxHp>old);});
test('HTML inneholder alle sentrale spillflater og mobilkontroller',()=>{for(const id of ['game','titleScreen','dialog','battleUI','teamPanel','questPanel','ending','mobileControls','actionBtn','itemBtn','berryCount','relicCount','reserveList'])assert.match(html,new RegExp(`id="${id}"`));assert.match(css,/pointer:coarse/);assert.match(css,/image-rendering:pixelated/);});
test('verden inneholder campingplass, skog og hule',()=>{for(const token of ['FURULY CAMPING','HVISKESKOGEN','GLØDESTEINSHULEN','areaAt'])assert.ok(game.includes(token));});
test('Ninni er synlig følgesvenn med følgebevegelse',()=>{for(const token of ['drawNinni','game.ninni','game.trail'])assert.ok(game.includes(token));});
test('kamp, fangst, lag på tre, bytting, seier og tap er implementert',()=>{for(const token of ['startBattle','attemptCapture','game.team.length<3','switchUnit','winBattle','loseBattle'])assert.ok(game.includes(token));});
test('historie, NPC-er, veiledning, boss og to avslutninger er implementert',()=>{for(const token of ['Bestemor Tora','Skogvokter Siv','Flammefyrsten','finishGame','Roglasset',"'befriended'","'defeated'",'Vennskapsprøven'])assert.ok(game.includes(token));});
test('Fjellroglasset gir garantert engangsvennskap med flokk eller reserve',()=>{for(const token of ['currentBossFriendship','FINN 3 SPOR','SVEKK MER','FJELLROGLAS','befriendBoss',"game.team.length<3","game.reserve.push(friend)","game.caught.includes('flammefyrsten')"])assert.ok(game.includes(token));});
test('bakoverkompatibel lagring og postgame beholder åpen verden',()=>{for(const token of ['endingType:game.endingType',"game.bossDefeated&&!game.endingType","game.endingType='defeated'","game.mode='world'","startBattle('flammefyrsten',4,true,game.bossDefeated)"])assert.ok(game.includes(token));});
test('responsiv sporbok skjuler uoppdagede og viser sju vennskapsstatuser',()=>{for(const id of ['bestiaryList','endingTitle'])assert.match(html,new RegExp(`id="${id}"`));for(const token of ['renderBestiary','Ukjent spor','Ikke oppdaget','★ VENN','◉ OPPDAGET'])assert.ok(game.includes(token));for(const token of ['bestiary-grid','bestiary-card','max-width:420px'])assert.ok(css.includes(token));});
test('lokal lagring, beste tid, lyd og debug-API finnes',()=>{for(const token of ['localStorage.setItem','BEST_KEY','AudioContext','VillsporDebug'])assert.ok(game.includes(token));});
test('sprintsystemer for villbær, glødespor, minikart og synlige skogshindre finnes',()=>{for(const token of ['useBerry','collectRelic','captureOdds','drawMiniMap','drawForestCanopy','drawRelic'])assert.ok(game.includes(token));assert.match(game,/relics:\[\]/);assert.match(game,/inventory:\{berries:2\}/);});
test('kampene har tydelige effekt- og statuslag',()=>{for(const token of ["?'burst':'hit'","kind:'heal'","kind:'capture'",'Skjold','Svekket'])assert.ok(game.includes(token));});
test('nye venner kan lagres i reserve og byttes inn uten å øke flokken over tre',()=>{for(const token of ['reserve:[]','game.reserve.push','bringReserve','setLeader','data-reserve'])assert.ok(game.includes(token));assert.match(game,/game\.team\.length<3/);});
test('alle sju originale skapningsillustrasjoner finnes som gyldige SVG-filer',()=>{for(const id of Object.values(core.CREATURES).map(c=>c.id)){const p=`./assets/creatures/${id}.svg`;assert.ok(fs.existsSync(p),p);const svg=fs.readFileSync(p,'utf8');assert.match(svg,/<svg/);assert.match(svg,/viewBox="0 0 256 256"/);}});
test('skapningsbilder brukes i canvas og paneler med fallback',()=>{for(const token of ['creatureArt','drawImage(art','creatureThumb','creature-fallback','onerror='])assert.ok(game.includes(token));});
test('mobilkontroller blokkerer callout og håndterer hele pointer-livssyklusen',()=>{for(const token of ['-webkit-touch-callout:none','touch-action:none','-webkit-user-select:none'])assert.ok(css.includes(token));for(const token of ['setPointerCapture','releasePointerCapture','pointercancel','lostpointercapture','contextmenu','selectstart','pointermove'])assert.ok(game.includes(token));});
test('lav landskapskamp har kompakt meny, skjulte retningsknapper og fullskjermvalg',()=>{assert.match(html,/id="fullscreenBtn"/);for(const token of ['data-game-mode="battle"','grid-template-areas:"status actions" "log actions"','max-height:104px'])assert.ok(css.includes(token));for(const token of ['toggleFullscreen','requestFullscreen','webkitRequestFullscreen','syncModeUI'])assert.ok(game.includes(token));});
test('JavaScript-filene kan parses',()=>{new vm.Script(fs.readFileSync('./game-core.js','utf8'));new vm.Script(game);});

let passed=0;
for(const [name,fn] of tests){try{await fn();passed++;console.log(`✓ ${name}`);}catch(err){console.error(`✗ ${name}\n  ${err.stack||err}`);process.exitCode=1;}}
console.log(`\n${passed}/${tests.length} tester bestått`);
if(passed!==tests.length)process.exit(1);
